import type { Track } from "@/lib/types";

export const marketFinanceTrack: Track = {
  id: "market-finance",
  title: "Finance de marché",
  description: "Les fondamentaux des marchés financiers, de A à Z.",
  emoji: "📈",
  color: "blue",
  lessons: [
    {
      id: "mf-found-l1-action",
      slug: "action",
      title: "L'action",
      description: "Comprendre ce qu'est une action et ce qu'elle représente",
      estimatedMinutes: 5,
      cards: [
        {
          id: "mf-found-l1-action-def",
          type: "definition",
          front: "Qu'est-ce qu'une action ?",
          back: "Titre de propriété représentant une fraction du capital d'une entreprise. L'actionnaire est copropriétaire, a droit aux dividendes distribués et au vote en assemblée générale.",
          difficulty: 1,
          tags: ["action", "equity"],
        },
        {
          id: "mf-found-l1-action-intuition",
          type: "intuition",
          front: "Comment penser à une action ?",
          back: "Acheter une action = devenir associé d'une entreprise. Tu profites de sa croissance (plus-value) et de ses bénéfices (dividendes), mais tu assumes aussi ses pertes. L'upside est illimité, la perte maximale est le capital investi.",
          difficulty: 1,
          tags: ["action", "risque"],
        },
        {
          id: "mf-found-l1-action-example",
          type: "example",
          front: "Exemple concret d'actionnaire",
          back: "Tu achètes 1 action LVMH à 800 €. Tu deviens propriétaire d'une fraction infinitésimale du groupe. Si LVMH distribue 12 € de dividende, tu reçois 12 €. Si le cours monte à 900 €, ta plus-value latente est de 100 €.",
          difficulty: 1,
          tags: ["action", "LVMH"],
        },
        {
          id: "mf-found-l1-action-iq",
          type: "interview-question",
          front: "Quelle est la différence entre une action et une obligation ?",
          back: "",
          difficulty: 1,
          tags: ["action", "obligation"],
        },
        {
          id: "mf-found-l1-action-ma",
          type: "model-answer",
          front: "Réponse : action vs obligation",
          back: "Action = part de capital (propriété, dividende variable, upside illimité, risque total). Obligation = prêt (créancier, coupon fixe, priorité en cas de faillite, capital remboursé à maturité). En cas de faillite, les obligataires sont remboursés avant les actionnaires.",
          difficulty: 1,
          tags: ["action", "obligation"],
        },
      ],
    },
    {
      id: "mf-found-l1-obligation",
      slug: "obligation",
      title: "L'obligation",
      description: "Comprendre ce qu'est une obligation et comment elle fonctionne",
      estimatedMinutes: 6,
      cards: [
        {
          id: "mf-found-l1-oblig-def",
          type: "definition",
          front: "Qu'est-ce qu'une obligation ?",
          back: "Titre de dette émis par une entreprise ou un État pour emprunter sur les marchés. L'investisseur prête de l'argent en échange d'un taux d'intérêt fixe (coupon) et récupère son capital à maturité.",
          difficulty: 1,
          tags: ["obligation", "dette"],
        },
        {
          id: "mf-found-l1-oblig-intuition",
          type: "intuition",
          front: "Comment penser à une obligation ?",
          back: "Obligation = prêt titrisé. Au lieu d'emprunter à une banque, l'émetteur emprunte directement aux investisseurs via les marchés. L'investisseur devient créancier (pas actionnaire) : il a un droit de remboursement prioritaire.",
          difficulty: 1,
          tags: ["obligation", "créancier"],
        },
        {
          id: "mf-found-l1-oblig-formula",
          type: "formula",
          front: "Composants d'une obligation",
          back: "• Valeur nominale : montant du prêt (ex: 1 000 €)\n• Coupon : intérêt annuel (ex: 3% × 1 000 = 30 €/an)\n• Maturité : durée du prêt (ex: 10 ans)\n• Prix de marché : varie inversement aux taux d'intérêt",
          difficulty: 1,
          tags: ["obligation", "coupon"],
        },
        {
          id: "mf-found-l1-oblig-example",
          type: "example",
          front: "L'OAT française 10 ans",
          back: "La France emprunte via les OAT (Obligations Assimilables du Trésor). En 2024, l'OAT 10 ans offrait ~3 % par an. Un investisseur prêtant 100 000 € reçoit 3 000 €/an pendant 10 ans, puis récupère ses 100 000 €.",
          difficulty: 1,
          tags: ["OAT", "France", "taux"],
        },
        {
          id: "mf-found-l1-oblig-trap",
          type: "trap",
          front: "Piège : taux qui monte = prix qui baisse",
          back: "Quand les taux d'intérêt montent, le prix des obligations existantes baisse (et inversement). Si tu détiens une obligation à 2 % et que les taux montent à 4 %, ton obligation vaut moins car les nouvelles émissions rapportent plus.",
          difficulty: 2,
          tags: ["obligation", "taux", "prix"],
        },
      ],
    },
    {
      id: "mf-found-l1-rendement",
      slug: "rendement",
      title: "Le rendement",
      description: "Calculer et interpréter le rendement d'un investissement",
      estimatedMinutes: 5,
      cards: [
        {
          id: "mf-found-l1-rend-def",
          type: "definition",
          front: "Qu'est-ce que le rendement ?",
          back: "Gain total d'un investissement exprimé en pourcentage du capital investi sur une période donnée. Il comprend les revenus (dividendes, coupons) et les plus ou moins-values.",
          difficulty: 1,
          tags: ["rendement"],
        },
        {
          id: "mf-found-l1-rend-formula",
          type: "formula",
          front: "Formule du rendement simple",
          back: "Rendement = (Plus-value + Revenus) / Capital investi × 100 %\n\nEx : achat 100 €, vente 110 €, dividende reçu 3 €\n→ Rendement = (10 + 3) / 100 = 13 %",
          difficulty: 1,
          tags: ["rendement", "calcul"],
        },
        {
          id: "mf-found-l1-rend-intuition",
          type: "intuition",
          front: "Rendement et risque sont indissociables",
          back: "Plus un investissement est risqué, plus les investisseurs exigent un rendement élevé pour compenser. C'est la prime de risque. Une OAT française à 3 % vs une obligation d'une PME à 8 % : l'écart rémunère le risque de défaut supplémentaire.",
          difficulty: 1,
          tags: ["rendement", "risque", "prime"],
        },
        {
          id: "mf-found-l1-rend-trap",
          type: "trap",
          front: "Piège : rendement brut ≠ rendement net",
          back: "Le rendement brut ignore les frais de courtage, la fiscalité (30 % flat tax en France) et l'inflation. Un rendement de 5 % brut peut devenir négatif en termes réels si l'inflation est à 6 %. Toujours raisonner en net réel.",
          difficulty: 2,
          tags: ["rendement", "fiscalité", "inflation"],
        },
      ],
    },
    {
      id: "mf-found-l1-risque",
      slug: "risque",
      title: "Le risque",
      description: "Identifier et comprendre les différents types de risques financiers",
      estimatedMinutes: 6,
      cards: [
        {
          id: "mf-found-l1-risque-def",
          type: "definition",
          front: "Qu'est-ce que le risque en finance ?",
          back: "Possibilité que le rendement réel d'un investissement diffère du rendement attendu. Le risque peut être quantifié par la volatilité (écart-type des rendements). On distingue : risque de marché, de crédit, de liquidité, opérationnel.",
          difficulty: 1,
          tags: ["risque", "volatilité"],
        },
        {
          id: "mf-found-l1-risque-example",
          type: "example",
          front: "Les 4 grands types de risques",
          back: "• Risque de marché : actions qui chutent lors d'un krach\n• Risque de crédit : émetteur qui fait défaut (ex : Lehman Brothers 2008)\n• Risque de liquidité : impossible de revendre rapidement sans décote\n• Risque opérationnel : erreur de trading, fraude (ex : Kerviel)",
          difficulty: 1,
          tags: ["risque", "crédit", "liquidité"],
        },
        {
          id: "mf-found-l1-risque-intuition",
          type: "intuition",
          front: "Risque ≠ perte certaine",
          back: "Le risque est l'incertitude du résultat, pas forcément une perte. Un actif risqué peut générer d'excellentes performances. Un actif 'sans risque apparent' peut cacher des risques non visibles (ex : un placement illiquide qui semble stable).",
          difficulty: 1,
          tags: ["risque", "incertitude"],
        },
        {
          id: "mf-found-l1-risque-iq",
          type: "interview-question",
          front: "Citez les principaux types de risques en finance de marché et donnez un exemple pour chacun.",
          back: "",
          difficulty: 1,
          tags: ["risque"],
        },
        {
          id: "mf-found-l1-risque-ma",
          type: "model-answer",
          front: "Réponse : types de risques",
          back: "Risque de marché (krach 2008 : -40 % sur les actions), risque de crédit (défaut Lehman Brothers), risque de liquidité (ABS devenus invendables en 2008), risque opérationnel (fraude Kerviel chez SG). On peut aussi citer le risque de contrepartie et le risque réglementaire.",
          difficulty: 1,
          tags: ["risque"],
        },
      ],
    },
    {
      id: "mf-found-l1-marche-primaire",
      slug: "marche-primaire",
      title: "Le marché primaire",
      description: "Comprendre comment les entreprises et États lèvent des capitaux",
      estimatedMinutes: 4,
      cards: [
        {
          id: "mf-found-l1-mp-def",
          type: "definition",
          front: "Qu'est-ce que le marché primaire ?",
          back: "Marché sur lequel de nouveaux titres (actions, obligations) sont émis et vendus pour la première fois aux investisseurs. C'est là que les émetteurs (entreprises, États) lèvent des capitaux directement.",
          difficulty: 1,
          tags: ["marché primaire"],
        },
        {
          id: "mf-found-l1-mp-intuition",
          type: "intuition",
          front: "Marché primaire = création de titres",
          back: "Lors d'une IPO, l'entreprise crée de nouvelles actions et les vend. L'argent va directement à l'entreprise. C'est du financement direct : l'entreprise n'emprunte pas à une banque, elle lève des fonds sur les marchés.",
          difficulty: 1,
          tags: ["IPO", "financement"],
        },
        {
          id: "mf-found-l1-mp-example",
          type: "example",
          front: "Exemples d'opérations de marché primaire",
          back: "• IPO : Arm Holdings sur le Nasdaq (sept. 2023, 54 Mds $)\n• Émission obligataire : la France émet des OAT régulièrement\n• Augmentation de capital : une entreprise émet de nouvelles actions pour financer une acquisition\n• Privatisation : État cède des parts d'une entreprise publique",
          difficulty: 1,
          tags: ["IPO", "OAT", "augmentation de capital"],
        },
      ],
    },
    {
      id: "mf-found-l1-marche-secondaire",
      slug: "marche-secondaire",
      title: "Le marché secondaire",
      description: "Comprendre le rôle de la Bourse dans l'échange de titres existants",
      estimatedMinutes: 4,
      cards: [
        {
          id: "mf-found-l1-ms-def",
          type: "definition",
          front: "Qu'est-ce que le marché secondaire ?",
          back: "Marché sur lequel s'échangent des titres déjà émis entre investisseurs. Aucun capital ne va à l'émetteur : c'est un simple transfert de propriété entre acheteur et vendeur. La Bourse est le principal marché secondaire.",
          difficulty: 1,
          tags: ["marché secondaire", "bourse"],
        },
        {
          id: "mf-found-l1-ms-intuition",
          type: "intuition",
          front: "Marché secondaire = liquidité pour les investisseurs",
          back: "Sans marché secondaire, un investisseur qui achète une obligation à 10 ans serait bloqué pendant 10 ans. La Bourse permet de revendre à tout moment. C'est ce qui rend les titres financiers attractifs : on peut sortir quand on veut.",
          difficulty: 1,
          tags: ["liquidité", "marché secondaire"],
        },
        {
          id: "mf-found-l1-ms-example",
          type: "example",
          front: "Marché secondaire au quotidien",
          back: "Quand tu achètes des actions Apple via un courtier, tu achètes à un autre investisseur via le NYSE (New York Stock Exchange). Apple ne reçoit rien : l'entreprise avait levé ses fonds lors de son IPO en 1980.",
          difficulty: 1,
          tags: ["Apple", "NYSE", "marché secondaire"],
        },
        {
          id: "mf-found-l1-ms-trap",
          type: "trap",
          front: "Piège : confondre les deux marchés",
          back: "Une IPO se passe sur le marché primaire, mais dès le 1er jour de cotation les échanges sur la Bourse sont du marché secondaire. Une augmentation de capital d'une entreprise déjà cotée est aussi du marché primaire (nouvelle émission).",
          difficulty: 1,
          tags: ["IPO", "marché primaire", "marché secondaire"],
        },
      ],
    },
    {
      id: "mf-found-l1-market-cap",
      slug: "capitalisation-boursiere",
      title: "La capitalisation boursière",
      description: "Calculer et interpréter la market cap d'une entreprise",
      estimatedMinutes: 4,
      cards: [
        {
          id: "mf-found-l1-cap-def",
          type: "definition",
          front: "Qu'est-ce que la capitalisation boursière ?",
          back: "Valeur totale de marché d'une entreprise cotée à un instant T. Elle se calcule : Cours de l'action × Nombre d'actions en circulation.",
          difficulty: 1,
          tags: ["market cap", "capitalisation"],
        },
        {
          id: "mf-found-l1-cap-formula",
          type: "formula",
          front: "Market Cap = Cours × Nombre d'actions",
          back: "Exemple LVMH (2024) :\nCours ≈ 750 € × 500 M d'actions ≈ 375 Mds €\n\nTop mondial 2024 :\n• Apple : ~3 000 Mds $\n• Microsoft : ~3 000 Mds $\n• Nvidia : ~2 000 Mds $",
          difficulty: 1,
          tags: ["market cap", "LVMH", "calcul"],
        },
        {
          id: "mf-found-l1-cap-intuition",
          type: "intuition",
          front: "Market cap ≠ valeur réelle de l'entreprise",
          back: "La market cap reflète ce que le marché est prêt à payer aujourd'hui, pas la 'valeur intrinsèque'. Elle change à chaque seconde. Une entreprise peut être surévaluée (bulle) ou sous-évaluée (opportunité). C'est le point de départ de la valorisation, pas la conclusion.",
          difficulty: 1,
          tags: ["valorisation", "market cap"],
        },
        {
          id: "mf-found-l1-cap-iq",
          type: "interview-question",
          front: "Comment calculez-vous la capitalisation boursière et quelles sont ses limites ?",
          back: "",
          difficulty: 1,
          tags: ["market cap"],
        },
        {
          id: "mf-found-l1-cap-ma",
          type: "model-answer",
          front: "Réponse : market cap et ses limites",
          back: "Market cap = cours × nombre d'actions. Limite principale : ne reflète que la valeur des capitaux propres, pas la dette. L'enterprise value (EV = market cap + dette nette) est plus pertinente pour comparer des entreprises avec des structures financières différentes.",
          difficulty: 1,
          tags: ["market cap", "enterprise value", "EV"],
        },
      ],
    },
    {
      id: "mf-found-l1-dividende",
      slug: "dividende",
      title: "Le dividende",
      description: "Comprendre comment les entreprises redistribuent leurs bénéfices",
      estimatedMinutes: 5,
      cards: [
        {
          id: "mf-found-l1-div-def",
          type: "definition",
          front: "Qu'est-ce qu'un dividende ?",
          back: "Part des bénéfices d'une entreprise redistribuée aux actionnaires. Décidé par le conseil d'administration et voté en AG. Versé en cash ou en actions. Son montant n'est pas garanti et peut être réduit ou supprimé.",
          difficulty: 1,
          tags: ["dividende"],
        },
        {
          id: "mf-found-l1-div-formula",
          type: "formula",
          front: "Dividend Yield = Dividende annuel / Cours × 100 %",
          back: "Exemple TotalEnergies (2024) :\nDividende annuel ≈ 3 € / cours 60 € = 5 % de yield\n\nInterprétation : pour 1 000 € investis, tu reçois 50 €/an en dividendes.",
          difficulty: 1,
          tags: ["dividend yield", "calcul"],
        },
        {
          id: "mf-found-l1-div-intuition",
          type: "intuition",
          front: "Dividende vs réinvestissement",
          back: "Une entreprise a deux choix avec ses bénéfices : distribuer (dividende) ou réinvestir (croissance). Les entreprises matures (TotalEnergies, LVMH) paient de forts dividendes. Les entreprises en forte croissance (Amazon longtemps, Nvidia) préfèrent réinvestir.",
          difficulty: 1,
          tags: ["dividende", "croissance"],
        },
        {
          id: "mf-found-l1-div-trap",
          type: "trap",
          front: "Piège : le yield élevé n'est pas toujours bon signe",
          back: "Un yield de 10 % peut indiquer que le cours a fortement chuté (dividende stable, cours en baisse). Le marché anticipe peut-être une coupe du dividende. On appelle ça un 'dividend trap'. Toujours vérifier si le dividende est soutenable (ratio de distribution).",
          difficulty: 2,
          tags: ["dividende", "yield", "dividend trap"],
        },
      ],
    },
    {
      id: "mf-found-l1-volume",
      slug: "volume",
      title: "Le volume",
      description: "Lire et interpréter les volumes de trading en bourse",
      estimatedMinutes: 4,
      cards: [
        {
          id: "mf-found-l1-vol-def",
          type: "definition",
          front: "Qu'est-ce que le volume en bourse ?",
          back: "Nombre de titres (actions, obligations) échangés sur un marché sur une période donnée (journée, semaine). Il mesure l'intensité de l'activité et l'intérêt des investisseurs pour un titre.",
          difficulty: 1,
          tags: ["volume", "trading"],
        },
        {
          id: "mf-found-l1-vol-intuition",
          type: "intuition",
          front: "Volume = confirmation d'une tendance",
          back: "Une hausse avec fort volume = signal haussier solide (beaucoup d'acheteurs). Une hausse avec faible volume = signal moins fiable (peu de participants). Le volume valide les mouvements de prix. C'est la différence entre un vrai mouvement et un 'faux signal'.",
          difficulty: 1,
          tags: ["volume", "tendance", "signal"],
        },
        {
          id: "mf-found-l1-vol-example",
          type: "example",
          front: "Lecture du volume sur le CAC 40",
          back: "Volume quotidien moyen du CAC 40 : ~3–5 milliards €. Lors d'une décision de la BCE ou d'annonces de résultats majeurs, le volume peut doubler. En été ou entre Noël et le Nouvel An, les volumes chutent : les prix sont moins représentatifs.",
          difficulty: 1,
          tags: ["CAC 40", "volume", "BCE"],
        },
      ],
    },
    {
      id: "mf-found-l1-liquidite",
      slug: "liquidite",
      title: "La liquidité",
      description: "Comprendre ce que signifie la liquidité et pourquoi elle est cruciale",
      estimatedMinutes: 5,
      cards: [
        {
          id: "mf-found-l1-liq-def",
          type: "definition",
          front: "Qu'est-ce que la liquidité d'un actif ?",
          back: "Facilité à acheter ou vendre un actif rapidement, en grande quantité, sans impacter significativement son prix. Un actif liquide = marché profond avec beaucoup d'acheteurs et vendeurs en permanence.",
          difficulty: 1,
          tags: ["liquidité"],
        },
        {
          id: "mf-found-l1-liq-intuition",
          type: "intuition",
          front: "Pourquoi la liquidité est-elle cruciale ?",
          back: "Imagine vouloir vendre une maison en 24h : tu dois brader le prix. Une action Apple se vend en millisecondes à son prix de marché. La liquidité = liberté de sortir quand on veut, au bon prix. Les marchés illiquides exigent une prime de risque supplémentaire.",
          difficulty: 1,
          tags: ["liquidité", "prime de risque"],
        },
        {
          id: "mf-found-l1-liq-example",
          type: "example",
          front: "Du plus liquide au moins liquide",
          back: "Forex (7 000 Mds $/jour) > Obligations d'État > Actions large cap (Apple, LVMH) > Small caps > Immobilier > Private Equity > Art\n\nLe Forex est le marché le plus liquide au monde. L'art peut prendre des mois à vendre.",
          difficulty: 1,
          tags: ["forex", "liquidité", "actifs"],
        },
        {
          id: "mf-found-l1-liq-trap",
          type: "trap",
          front: "Piège : la liquidité peut s'évaporer",
          back: "En période de stress, la liquidité peut disparaître brutalement. En 2008, des actifs réputés liquides (certains ABS) sont devenus totalement invendables. Jamais supposer qu'un actif restera liquide en crise. C'est le risque de liquidité.",
          difficulty: 2,
          tags: ["liquidité", "risque", "2008"],
        },
        {
          id: "mf-found-l1-liq-iq",
          type: "interview-question",
          front: "Comment évaluez-vous le risque de liquidité d'un actif ? Quels indicateurs utilisez-vous ?",
          back: "",
          difficulty: 1,
          tags: ["liquidité", "risque"],
        },
        {
          id: "mf-found-l1-liq-ma",
          type: "model-answer",
          front: "Réponse : évaluer le risque de liquidité",
          back: "J'utilise le spread bid-ask (plus il est large, moins c'est liquide), les volumes journaliers moyens, la profondeur du carnet d'ordres et le nombre de market makers. Je regarde aussi le comportement en période de stress passé. Un actif peut sembler liquide en temps normal et devenir illiquide en crise (risk-off).",
          difficulty: 2,
          tags: ["liquidité", "bid-ask", "spread"],
        },
      ],
    },
    {
      id: "mf-found-l1-buyside-sellside",
      slug: "buy-side-sell-side",
      title: "Buy-side vs Sell-side",
      description: "Distinguer les deux grandes familles d'acteurs en finance de marché",
      estimatedMinutes: 5,
      cards: [
        {
          id: "mf-found-l1-bss-def",
          type: "definition",
          front: "Quelle est la différence entre buy-side et sell-side ?",
          back: "Sell-side : institutions qui vendent des services financiers (exécution, recherche, conseil, structuration). Ex : banques d'investissement, brokers.\n\nBuy-side : institutions qui achètent et gèrent des actifs pour le compte de clients. Ex : hedge funds, asset managers, fonds de pension.",
          difficulty: 1,
          tags: ["buy-side", "sell-side"],
        },
        {
          id: "mf-found-l1-bss-intuition",
          type: "intuition",
          front: "Le sell-side sert le buy-side",
          back: "Goldman Sachs Sales & Trading (sell-side) exécute les ordres de BlackRock (buy-side). Le sell-side est rémunéré par des commissions et spreads. Le buy-side est rémunéré par des frais de gestion (management fee ~2 %) et une commission de performance (carried interest ~20 %).",
          difficulty: 1,
          tags: ["buy-side", "sell-side", "frais"],
        },
        {
          id: "mf-found-l1-bss-example",
          type: "example",
          front: "Exemples d'acteurs des deux côtés",
          back: "Sell-side : Goldman Sachs, JP Morgan, BNP Paribas CIB, Morgan Stanley, Société Générale CIB, Rothschild.\n\nBuy-side : BlackRock, Vanguard, Fidelity, Amundi, AXA IM, Citadel, Bridgewater, Tiger Global.",
          difficulty: 1,
          tags: ["Goldman Sachs", "BlackRock", "buy-side", "sell-side"],
        },
        {
          id: "mf-found-l1-bss-iq",
          type: "interview-question",
          front: "Quelle est la différence entre buy-side et sell-side ? Où souhaitez-vous travailler et pourquoi ?",
          back: "",
          difficulty: 1,
          tags: ["buy-side", "sell-side", "carrière"],
        },
        {
          id: "mf-found-l1-bss-ma",
          type: "model-answer",
          front: "Réponse : buy-side vs sell-side",
          back: "Le sell-side fournit des services (exécution d'ordres, recherche, conseil en levée de fonds) et est rémunéré par des commissions. Le buy-side gère des actifs pour maximiser la performance de ses clients et est rémunéré par management fees et performance fees. Le buy-side décide des investissements, le sell-side les facilite.",
          difficulty: 1,
          tags: ["buy-side", "sell-side"],
        },
      ],
    },
    {
      id: "mf-found-l1-acteurs",
      slug: "acteurs-du-marche",
      title: "Les acteurs du marché",
      description: "Identifier qui opère sur les marchés financiers et leurs motivations",
      estimatedMinutes: 5,
      cards: [
        {
          id: "mf-found-l1-act-def",
          type: "definition",
          front: "Qui sont les acteurs des marchés financiers ?",
          back: "• Sell-side : banques d'investissement, brokers, market makers\n• Buy-side institutionnel : asset managers, hedge funds, fonds de pension, assureurs\n• Banques centrales : Fed, BCE (interventions ponctuelles mais impactantes)\n• Retail : investisseurs particuliers\n• Gouvernements : via les émissions de dette publique",
          difficulty: 1,
          tags: ["acteurs", "institutionnel"],
        },
        {
          id: "mf-found-l1-act-example",
          type: "example",
          front: "Poids relatif des acteurs",
          back: "• Institutionnels (buy-side) : ~80 % des volumes mondiaux\n• Retail : ~15–20 % (en hausse avec Robinhood, Trade Republic)\n• HFT (High Frequency Trading) : ~50 % des volumes actions US\n• Banques centrales : faible volume mais impact maximal sur les prix",
          difficulty: 1,
          tags: ["institutionnel", "retail", "HFT"],
        },
        {
          id: "mf-found-l1-act-intuition",
          type: "intuition",
          front: "Chaque acteur a des motivations différentes",
          back: "Un fonds de pension investit sur 30 ans pour payer les retraites. Un hedge fund macro peut shorter un pays entier sur 3 mois. Un market maker achète et revend en millisecondes pour capturer le spread. Comprendre les motivations de chaque acteur aide à anticiper leurs comportements.",
          difficulty: 1,
          tags: ["motivations", "fonds de pension", "hedge fund"],
        },
        {
          id: "mf-found-l1-act-iq",
          type: "interview-question",
          front: "Décrivez les principaux acteurs des marchés financiers et expliquez leurs motivations respectives.",
          back: "",
          difficulty: 1,
          tags: ["acteurs"],
        },
      ],
    },
  ],
};
