import type { Lesson } from "@/lib/types";

export const lessonBossWorld1: Lesson = {
  id: "mf-boss-1-market-basics",
  slug: "boss-market-basics",
  title: "Boss 1 — Bases des marchés",
  description: "Valider les notions fondamentales du premier monde.",
  estimatedMinutes: 10,
  kind: "boss",
  worldId: "mf-world-1-market-basics",
  order: 13,
  cards: [
    {
      id: "mf-boss-1-financial-market-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'un marché financier ?",
      shortAnswer:
        "Un marché financier est un lieu physique ou électronique où des acheteurs et des vendeurs échangent des actifs financiers à un prix de marché.",
      explanation:
        "Le marché sert à former les prix, transférer le risque et permettre aux entreprises ou États de se financer. Il peut être organisé en bourse ou de gré à gré.",
      front: "Qu'est-ce qu'un marché financier ?",
      back: "Un marché financier est un lieu physique ou électronique où des acheteurs et des vendeurs échangent des actifs financiers à un prix de marché.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché", "prix", "actifs-financiers"],
      skills: ["definition"],
      tags: ["marché", "prix"],
    },
    {
      id: "mf-boss-1-equity-bond-comparison",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence fondamentale entre une action et une obligation ?",
      shortAnswer:
        "Une action représente une part de propriété dans une entreprise. Une obligation représente une dette : l'investisseur prête de l'argent et devient créancier.",
      explanation:
        "L'actionnaire a un upside plus élevé mais passe après les créanciers en cas de faillite. L'obligataire reçoit généralement des coupons et est prioritaire dans la structure de capital.",
      front: "Quelle est la différence fondamentale entre une action et une obligation ?",
      back: "Une action représente une part de propriété. Une obligation représente une dette : l'investisseur prête de l'argent et devient créancier.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "obligation", "structure-du-capital"],
      skills: ["comparison"],
      tags: ["action", "obligation"],
    },
    {
      id: "mf-boss-1-total-return-formula",
      type: "formula",
      questionType: "formula",
      question: "Comment calcule-t-on le rendement total d'un investissement ?",
      shortAnswer:
        "Le rendement total compare le gain global au capital investi, en incluant la variation de prix et les revenus reçus.",
      formula: "Rendement total = (Prix final - Prix initial + Revenus) / Prix initial",
      example: "Achat 100, vente 110, dividende 3 : rendement = (110 - 100 + 3) / 100 = 13 %.",
      front: "Comment calcule-t-on le rendement total d'un investissement ?",
      back: "Rendement total = (Prix final - Prix initial + Revenus) / Prix initial.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "performance", "dividende"],
      skills: ["formula"],
      tags: ["rendement", "calcul"],
    },
    {
      id: "mf-boss-1-risk-return-mechanism",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi rendement attendu et risque sont-ils liés ?",
      shortAnswer:
        "Plus un investissement est risqué, plus les investisseurs exigent un rendement attendu élevé pour accepter ce risque.",
      explanation:
        "Cette compensation s'appelle une prime de risque. Une obligation d'État solide paie moins qu'une obligation high yield car le risque de défaut est plus faible.",
      front: "Pourquoi rendement attendu et risque sont-ils liés ?",
      back: "Plus un investissement est risqué, plus les investisseurs exigent un rendement attendu élevé pour accepter ce risque.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "rendement", "prime-de-risque"],
      skills: ["mechanism"],
      tags: ["risque", "rendement"],
    },
    {
      id: "mf-boss-1-primary-secondary-comparison",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre marché primaire et marché secondaire ?",
      shortAnswer:
        "Le marché primaire sert à émettre de nouveaux titres. Le marché secondaire sert à échanger des titres déjà émis entre investisseurs.",
      explanation:
        "Une IPO ou une émission obligataire a lieu sur le primaire. Les échanges quotidiens en bourse ont lieu sur le secondaire.",
      front: "Quelle est la différence entre marché primaire et marché secondaire ?",
      back: "Le primaire sert à émettre de nouveaux titres. Le secondaire sert à échanger des titres déjà émis.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-primaire", "marché-secondaire", "émission"],
      skills: ["comparison"],
      tags: ["marché-primaire", "marché-secondaire"],
    },
    {
      id: "mf-boss-1-market-cap-formula",
      type: "formula",
      questionType: "formula",
      question: "Comment calcule-t-on la capitalisation boursière ?",
      shortAnswer:
        "La capitalisation boursière est la valeur de marché de l'equity d'une entreprise cotée.",
      formula: "Capitalisation boursière = Prix de l'action × Nombre d'actions en circulation",
      commonMistake:
        "Ne pas confondre prix unitaire de l'action et taille de l'entreprise : une action à 500 euros peut représenter une entreprise plus petite qu'une action à 20 euros.",
      front: "Comment calcule-t-on la capitalisation boursière ?",
      back: "Capitalisation boursière = Prix de l'action × Nombre d'actions en circulation.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "action", "valeur-de-marché"],
      skills: ["formula"],
      tags: ["capitalisation", "action"],
    },
    {
      id: "mf-boss-1-volume-liquidity-comparison",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre volume et liquidité ?",
      shortAnswer:
        "Le volume mesure la quantité échangée. La liquidité mesure la facilité à acheter ou vendre rapidement sans trop déplacer le prix.",
      explanation:
        "Un actif très liquide a souvent beaucoup de volume, un carnet d'ordres profond et un spread serré.",
      front: "Quelle est la différence entre volume et liquidité ?",
      back: "Le volume mesure la quantité échangée. La liquidité mesure la facilité à acheter ou vendre rapidement sans trop déplacer le prix.",
      difficulty: 1,
      learningStage: 1,
      topics: ["volume", "liquidité", "marché-secondaire"],
      skills: ["comparison"],
      tags: ["volume", "liquidité"],
    },
    {
      id: "mf-boss-1-dividend-definition",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'un dividende ?",
      shortAnswer:
        "Un dividende est une partie du bénéfice distribuée aux actionnaires, généralement en cash, après décision de l'entreprise.",
      commonMistake:
        "Un dividende élevé n'est pas toujours bon signe : il peut aussi refléter peu d'opportunités de croissance ou une forte baisse du cours.",
      front: "Qu'est-ce qu'un dividende ?",
      back: "Un dividende est une partie du bénéfice distribuée aux actionnaires, généralement en cash.",
      difficulty: 1,
      learningStage: 1,
      topics: ["dividende", "action", "rendement"],
      skills: ["definition"],
      tags: ["dividende", "action"],
    },
    {
      id: "mf-boss-1-buyside-sellside-comparison",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre buy-side et sell-side ?",
      shortAnswer:
        "Le buy-side gère ou investit du capital. Le sell-side fournit des services de marché, de recherche, d'exécution ou de structuration.",
      explanation:
        "Un asset manager ou hedge fund est buy-side. Une banque d'investissement, un broker ou une desk de market making est sell-side.",
      front: "Quelle est la différence entre buy-side et sell-side ?",
      back: "Le buy-side gère ou investit du capital. Le sell-side fournit des services de marché, de recherche, d'exécution ou de structuration.",
      difficulty: 1,
      learningStage: 1,
      topics: ["buy-side", "sell-side", "acteurs"],
      skills: ["comparison"],
      tags: ["buy-side", "sell-side"],
    },
    {
      id: "mf-boss-1-market-actors-mechanism",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi la diversité des acteurs aide-t-elle le marché à fonctionner ?",
      shortAnswer:
        "Des acteurs avec horizons et objectifs différents créent naturellement des acheteurs et des vendeurs, donc de la liquidité et de la formation de prix.",
      explanation:
        "Un fonds de pension peut investir sur 30 ans, un hedge fund sur quelques semaines et un market maker sur quelques secondes. Ces motivations différentes rendent l'échange possible.",
      front: "Pourquoi la diversité des acteurs aide-t-elle le marché à fonctionner ?",
      back: "Des acteurs avec horizons et objectifs différents créent des acheteurs et des vendeurs, donc de la liquidité et de la formation de prix.",
      difficulty: 1,
      learningStage: 1,
      topics: ["acteurs", "liquidité", "formation-des-prix"],
      skills: ["mechanism"],
      tags: ["acteurs", "liquidité"],
    },
  ],
};
