import type { Lesson } from "@/lib/types";

export const lessonBossWorld2: Lesson = {
  id: "mf-boss-2-instruments",
  slug: "boss-world-2",
  title: "Boss : Instruments et Valorisation",
  description:
    "Défi final du Monde 2 — indices, ETF, courbe des taux, valorisation, options, futures et forex",
  estimatedMinutes: 13,
  kind: "boss",
  worldId: "mf-world-2-instruments",
  cards: [
    {
      id: "mf-boss-2-mcq-01",
      type: "definition",
      questionType: "definition",
      question: "L'indice Dow Jones Industrial Average est pondéré par...",
      shortAnswer:
        "Le prix des actions (price-weighted). Une action plus chère pèse davantage, indépendamment de la taille de l'entreprise.",
      explanation:
        "C'est la méthode originale de 1896 et c'est aujourd'hui considérée comme dépassée. Le S&P 500 et la plupart des indices modernes utilisent la pondération par capitalisation boursière.",
      front: "L'indice Dow Jones Industrial Average est pondéré par...",
      back: "Le prix unitaire des actions (price-weighted).",
      difficulty: 1,
      learningStage: 1,
      topics: ["indices", "Dow-Jones"],
      skills: ["definition"],
      tags: ["indices", "Dow-Jones", "price-weighted"],
      choices: [
        "Le prix unitaire des actions (price-weighted)",
        "La capitalisation boursière flottante",
        "Le chiffre d'affaires des entreprises",
        "Le nombre d'actions en circulation",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-boss-2-tf-02",
      type: "definition",
      questionType: "true-false",
      question:
        "Un ETF se négocie comme une action ordinaire, en continu pendant les heures de bourse.",
      shortAnswer:
        "Vrai. C'est la caractéristique fondamentale des ETF par rapport aux fonds traditionnels.",
      explanation:
        "Les fonds traditionnels (FCP, SICAV) ne se souscrivent qu'une fois par jour à la valeur liquidative de clôture. Les ETF se négocient en temps réel avec un prix qui fluctue toute la journée.",
      correctBool: true,
      front: "Un ETF se négocie en continu pendant les heures de bourse.",
      back: "Vrai. Contrairement aux FCP/SICAV (une seule valeur liquidative par jour).",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "bourse", "liquidité"],
      skills: ["definition"],
      tags: ["ETF", "cotation", "liquidité"],
    },
    {
      id: "mf-boss-2-mcq-03",
      type: "definition",
      questionType: "mechanism",
      question: "Qu'est-ce qu'une courbe des taux inversée signale généralement ?",
      shortAnswer: "Une récession probable à horizon 6-18 mois.",
      explanation:
        "Historiquement, l'inversion du spread UST 10-2 ans a précédé toutes les récessions américaines depuis 1950. En 2022-2023, cette courbe a été la plus inversée depuis les années 1980.",
      front: "Qu'est-ce qu'une courbe des taux inversée signale généralement ?",
      back: "Une récession probable à horizon 6-18 mois.",
      difficulty: 1,
      learningStage: 1,
      topics: ["taux", "courbe-des-taux", "récession"],
      skills: ["mechanism"],
      tags: ["taux", "inversion", "récession"],
      choices: [
        "Une récession probable à horizon 6-18 mois",
        "Une période d'inflation forte et durable",
        "Un marché actions en forte hausse",
        "Une expansion économique accélérée",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-boss-2-tf-04",
      type: "definition",
      questionType: "true-false",
      question:
        "Le multiple EV/EBITDA est préféré au P/E pour comparer des entreprises avec des niveaux d'endettement différents.",
      shortAnswer:
        "Vrai. L'EBITDA est avant intérêts, donc indépendant de la structure de financement. Le P/E est affecté par la dette (les intérêts réduisent le bénéfice net).",
      explanation:
        "C'est pourquoi le M&A et le private equity travaillent quasi-exclusivement avec des multiples EV/EBITDA. Deux entreprises identiques sur le plan opérationnel mais avec des dettes différentes auront le même EV/EBITDA mais des P/E très différents.",
      correctBool: true,
      front: "EV/EBITDA est préféré au P/E pour comparer des entreprises avec des dettes différentes.",
      back: "Vrai. EV/EBITDA est neutre vis-à-vis de la structure de financement.",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "EV/EBITDA", "P/E"],
      skills: ["comparison"],
      tags: ["EV/EBITDA", "valorisation", "M&A"],
    },
    {
      id: "mf-boss-2-mcq-05",
      type: "definition",
      questionType: "mechanism",
      question: "L'acheteur d'un put profite si...",
      shortAnswer: "Le cours du sous-jacent baisse en dessous du strike.",
      explanation:
        "Un put = droit de vendre au strike. Si le cours tombe à 40 € avec un strike à 60 €, on peut acheter le sous-jacent à 40 € et le vendre via l'option à 60 € → gain = 20 € − prime payée.",
      front: "L'acheteur d'un put profite si...",
      back: "Le cours du sous-jacent baisse en dessous du strike.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "put", "profil-gains"],
      skills: ["mechanism"],
      tags: ["options", "put", "baisse"],
      choices: [
        "Le cours du sous-jacent baisse en dessous du strike",
        "Le cours du sous-jacent monte au-dessus du strike",
        "La volatilité implicite baisse fortement",
        "Le temps restant jusqu'à l'échéance augmente",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-boss-2-tf-06",
      type: "definition",
      questionType: "true-false",
      question:
        "Le 'marking to market' d'un futures implique que les gains et pertes sont réglés quotidiennement en cash.",
      shortAnswer:
        "Vrai. Contrairement à une obligation qu'on peut détenir sans reconnaître les pertes latentes, les futures génèrent des flux de trésorerie quotidiens réels.",
      explanation:
        "Ce mécanisme élimine le risque de contrepartie accumulé : chaque soir, les comptes de marge sont ajustés. Si un opérateur ne peut pas alimenter son compte, sa position est liquidée avant que les pertes deviennent trop importantes.",
      correctBool: true,
      front: "Le marking to market d'un futures implique un règlement quotidien des gains et pertes.",
      back: "Vrai. C'est un mécanisme anti-risque de contrepartie.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "marking-to-market"],
      skills: ["mechanism"],
      tags: ["futures", "marking-to-market", "marge"],
    },
    {
      id: "mf-boss-2-num-07",
      type: "formula",
      questionType: "quick-calculation",
      question: "EUR/USD = 1,05. Combien vaut 1 000 $ en euros ?",
      shortAnswer: "Environ 952 €.",
      formula: "Montant en EUR = Montant en USD / Taux EUR/USD",
      example: "1 000 / 1,05 ≈ 952,38 €",
      answerMode: "numeric",
      expectedAnswer: 952,
      answerUnit: "€",
      tolerance: 2,
      front: "EUR/USD = 1,05. Combien vaut 1 000 $ en euros ?",
      back: "Environ 952 €.",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "calcul", "EUR/USD"],
      skills: ["quick-calculation"],
      tags: ["change", "EUR/USD", "calcul"],
    },
    {
      id: "mf-boss-2-mcq-08",
      type: "definition",
      questionType: "definition",
      question:
        "Qu'est-ce que l'Enterprise Value (EV) inclut que la capitalisation boursière n'inclut pas ?",
      shortAnswer: "La dette nette (dettes financières moins trésorerie).",
      explanation:
        "EV = Market Cap + Dette nette. L'EV représente le prix total pour acquérir 100 % d'une entreprise : en rachetant une société, vous héritez de ses dettes et récupérez sa trésorerie. La market cap ne reflète que la valeur pour les actionnaires.",
      front: "Qu'est-ce que l'EV inclut que la market cap n'inclut pas ?",
      back: "La dette nette (dettes − trésorerie).",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "EV", "dette"],
      skills: ["definition"],
      tags: ["EV", "capitalisation", "dette"],
      choices: [
        "La dette nette (dettes − trésorerie)",
        "Les dividendes versés aux actionnaires",
        "La valeur des actifs incorporels (brevets, marques)",
        "Le bénéfice non distribué (réserves)",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-boss-2-tf-09",
      type: "definition",
      questionType: "true-false",
      question: "La perte maximale de l'acheteur d'un call est illimitée.",
      shortAnswer:
        "Faux. La perte maximale de l'acheteur d'un call est limitée à la prime payée. C'est si le cours reste sous le strike jusqu'à l'échéance.",
      explanation:
        "L'acheteur d'un call perd au maximum la prime payée (si l'option expire sans valeur). C'est le vendeur du call qui supporte un risque illimité en théorie (si le cours monte indéfiniment).",
      correctBool: false,
      front: "La perte maximale de l'acheteur d'un call est illimitée.",
      back: "Faux. Elle est limitée à la prime payée. Le risque illimité est du côté du vendeur du call.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "call", "risque"],
      skills: ["definition"],
      tags: ["options", "call", "prime"],
    },
    {
      id: "mf-boss-2-num-10",
      type: "formula",
      questionType: "quick-calculation",
      question:
        "Vous êtes acheteur d'1 contrat futures pétrole (1 000 barils) à 85 $/baril. Le cours monte à 88 $/baril. Quel est votre gain ?",
      shortAnswer: "3 000 $.",
      formula: "Gain = (Prix final − Prix initial) × Taille du contrat",
      example: "(88 − 85) × 1 000 = 3 × 1 000 = 3 000 $",
      answerMode: "numeric",
      expectedAnswer: 3000,
      answerUnit: "$",
      tolerance: 0.01,
      front: "Futures pétrole, 1 contrat (1 000 barils), achat à 85 $, cours monte à 88 $. Gain ?",
      back: "3 000 $.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "calcul", "P&L"],
      skills: ["quick-calculation"],
      tags: ["futures", "pétrole", "calcul"],
    },
    {
      id: "mf-boss-2-mcq-11",
      type: "definition",
      questionType: "mechanism",
      question: "Le QE (Quantitative Easing) vise principalement à...",
      shortAnswer:
        "Faire baisser les taux d'intérêt à long terme en rachetant des obligations, et injecter des liquidités dans l'économie.",
      explanation:
        "Quand les taux directeurs ne peuvent plus baisser (plancher zéro), la banque centrale rachète des obligations pour comprimer les taux longs. Cela stimule le crédit, l'investissement et (en théorie) l'économie réelle.",
      front: "Le QE vise principalement à...",
      back: "Faire baisser les taux longs en rachetant des obligations et injecter des liquidités.",
      difficulty: 1,
      learningStage: 1,
      topics: ["taux", "QE", "banque-centrale"],
      skills: ["mechanism"],
      tags: ["QE", "taux", "banque-centrale"],
      choices: [
        "Faire baisser les taux longs et injecter des liquidités",
        "Augmenter les taux courts pour contrôler l'inflation",
        "Financer directement les déficits publics",
        "Stabiliser le taux de change de la monnaie nationale",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-boss-2-tf-12",
      type: "definition",
      questionType: "true-false",
      question:
        "Un investisseur qui achète un ETF S&P 500 est exposé à la performance d'environ 500 entreprises américaines.",
      shortAnswer:
        "Vrai. L'ETF réplique le S&P 500, qui regroupe les ~500 plus grandes entreprises américaines cotées.",
      explanation:
        "C'est l'intérêt de la diversification via les ETF : avec une seule transaction, on s'expose à des centaines d'entreprises. Le risque spécifique à chaque entreprise est quasi-éliminé ; reste le risque systématique du marché.",
      correctBool: true,
      front: "Acheter un ETF S&P 500 expose à environ 500 entreprises américaines.",
      back: "Vrai. Diversification instantanée sur les ~500 plus grandes capitalisations US.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "diversification", "S&P500"],
      skills: ["definition"],
      tags: ["ETF", "S&P500", "diversification"],
    },
  ],
};
