import type { Lesson } from "@/lib/types";

export const lessonAction: Lesson = {
  id: "mf-found-l1-action",
  slug: "action",
  title: "L'action",
  description: "Comprendre ce qu'est une action et ce qu'elle représente",
  estimatedMinutes: 7,
  cards: [
    {
      id: "mf-found-l1-action-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'une action ?",
      shortAnswer:
        "Une action est un titre de propriété représentant une fraction du capital d'une entreprise.",
      explanation:
        "L'actionnaire est copropriétaire : il peut recevoir des dividendes, voter en assemblée générale et profiter d'une hausse du cours. En contrepartie, il supporte le risque résiduel : en cas de faillite, il passe après les créanciers.",
      front: "Qu'est-ce qu'une action ?",
      back: "Une action est un titre de propriété représentant une fraction du capital d'une entreprise.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "equity", "capital"],
      skills: ["definition"],
      tags: ["action", "equity"],
    },
    {
      id: "mf-found-l1-action-intuition",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi dit-on qu'acheter une action revient à devenir associé d'une entreprise ?",
      shortAnswer:
        "Parce que l'actionnaire détient une part du capital : il participe à la création de valeur, mais supporte aussi le risque économique de l'entreprise.",
      explanation:
        "Si l'entreprise grandit, le cours peut monter et l'actionnaire peut toucher des dividendes. Si elle va mal, le cours baisse et la perte peut aller jusqu'au capital investi.",
      front: "Pourquoi dit-on qu'acheter une action revient à devenir associé d'une entreprise ?",
      back: "Parce que l'actionnaire détient une part du capital : il participe à la création de valeur, mais supporte aussi le risque économique de l'entreprise.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "risque", "plus-value"],
      skills: ["mechanism"],
      tags: ["action", "risque"],
    },
    {
      id: "mf-found-l1-action-example",
      type: "example",
      questionType: "quick-calculation",
      question: "Vous achetez une action à 800 euros et elle monte à 900 euros. Quelle est votre plus-value ?",
      shortAnswer:
        "La plus-value est de 100 euros par action, avant impôts et frais.",
      formula: "Plus-value = Prix de vente - Prix d'achat",
      example:
        "Si vous possédez 10 actions, la plus-value latente est 10 × 100 = 1 000 euros.",
      front: "Vous achetez une action à 800 euros et elle monte à 900 euros. Quelle est votre plus-value ?",
      back: "La plus-value est de 100 euros par action, avant impôts et frais.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "p&l", "plus-value"],
      skills: ["quick-calculation"],
      tags: ["action", "p&l"],
    },
    {
      id: "mf-found-l1-action-trap",
      type: "definition",
      questionType: "definition",
      question: "Une action sans dividende est-elle forcément une mauvaise action ?",
      shortAnswer:
        "Non. Une entreprise peut créer de la valeur en réinvestissant ses bénéfices plutôt qu'en les distribuant.",
      explanation:
        "Les entreprises de croissance privilégient souvent l'investissement, la R&D ou les acquisitions. La rémunération de l'actionnaire peut alors venir surtout de la hausse du cours.",
      commonMistake:
        "Ne pas confondre absence de dividende et absence de création de valeur.",
      front: "Une action sans dividende est-elle forcément une mauvaise action ?",
      back: "Non. Une entreprise peut créer de la valeur en réinvestissant ses bénéfices plutôt qu'en les distribuant.",
      difficulty: 2,
      learningStage: 1,
      topics: ["action", "dividende", "croissance"],
      skills: ["definition"],
      tags: ["action", "dividende", "croissance"],
    },
    {
      id: "mf-found-l1-action-iq",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre une action et une obligation ?",
      shortAnswer:
        "Une action est une part de capital : l'investisseur est propriétaire. Une obligation est une dette : l'investisseur est créancier.",
      explanation:
        "L'action offre un potentiel de hausse plus élevé mais passe après la dette en cas de faillite. L'obligation verse généralement un coupon et a une priorité de remboursement supérieure.",
      front: "Quelle est la différence entre une action et une obligation ?",
      back: "Une action est une part de capital : l'investisseur est propriétaire. Une obligation est une dette : l'investisseur est créancier.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "obligation", "capital"],
      skills: ["comparison"],
      tags: ["action", "obligation"],
    },
    {
      id: "mf-found-l1-action-ma",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi l'actionnaire exige-t-il généralement un rendement supérieur à l'obligataire ?",
      shortAnswer:
        "Parce que l'actionnaire porte le risque résiduel : il est servi après les créanciers et son rendement n'est pas contractuel.",
      explanation:
        "Le coupon obligataire est prévu à l'avance, alors que dividendes et plus-values sont incertains. Cette incertitude justifie une prime de risque equity.",
      front: "Pourquoi l'actionnaire exige-t-il généralement un rendement supérieur à l'obligataire ?",
      back: "Parce que l'actionnaire porte le risque résiduel : il est servi après les créanciers et son rendement n'est pas contractuel.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "obligation", "prime-de-risque"],
      skills: ["mechanism"],
      tags: ["action", "obligation"],
    },
    {
      id: "mf-found-l1-action-tf-1",
      type: "definition",
      questionType: "true-false",
      question: "Une action sans dividende est forcément un mauvais investissement.",
      shortAnswer: "Faux. Une entreprise peut créer de la valeur en réinvestissant ses bénéfices plutôt qu'en les distribuant.",
      explanation: "Les entreprises de croissance (Amazon, Nvidia) ont longtemps versé zéro dividende tout en offrant d'excellentes performances.",
      correctBool: false,
      front: "Une action sans dividende est forcément un mauvais investissement.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "dividende"],
      skills: ["definition"],
      tags: ["action", "dividende"],
    },
    {
      id: "mf-found-l1-action-num-1",
      type: "formula",
      questionType: "quick-calculation",
      question: "Vous achetez 50 actions à 20 € et les revendez à 25 €. Quelle est votre plus-value totale ?",
      shortAnswer: "250 €",
      formula: "Plus-value = (Prix de vente − Prix d'achat) × Nombre d'actions",
      example: "(25 − 20) × 50 = 5 × 50 = 250 €",
      answerMode: "numeric",
      expectedAnswer: 250,
      answerUnit: "€",
      tolerance: 0.01,
      front: "Vous achetez 50 actions à 20 € et les revendez à 25 €. Quelle est votre plus-value totale ?",
      back: "250 €",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "plus-value", "calcul"],
      skills: ["quick-calculation"],
      tags: ["action", "calcul"],
    },
    {
      id: "mf-found-l1-action-mcq-1",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que détenir une action confère à l'investisseur ?",
      shortAnswer: "Une fraction de la propriété de l'entreprise.",
      explanation:
        "Être actionnaire signifie être copropriétaire. Cela donne droit au dividende (si distribué), à une part de l'actif net en cas de liquidation, et généralement au droit de vote en assemblée générale.",
      front: "Qu'est-ce que détenir une action confère à l'investisseur ?",
      back: "Une fraction de la propriété de l'entreprise.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action"],
      skills: ["definition"],
      tags: ["action"],
      choices: [
        "Une fraction de la propriété de l'entreprise",
        "Un droit de créance prioritaire sur les actifs",
        "Un coupon fixe versé chaque année",
        "Une garantie de remboursement du capital investi",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-action-tf-2",
      type: "definition",
      questionType: "true-false",
      question: "En cas de faillite d'une entreprise, l'actionnaire est remboursé avant les créanciers obligataires.",
      shortAnswer: "Faux. L'actionnaire est créancier résiduel : il est remboursé en dernier, après tous les créanciers.",
      explanation: "La hiérarchie de remboursement en faillite : créanciers séniors → créanciers subordonnés → obligataires → actionnaires. En pratique, il reste souvent rien pour les actionnaires.",
      correctBool: false,
      front: "En cas de faillite d'une entreprise, l'actionnaire est remboursé avant les créanciers obligataires.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "faillite", "créancier"],
      skills: ["definition"],
      tags: ["action", "risque"],
    },
    {
      id: "mf-found-l1-action-mcq-2",
      type: "definition",
      questionType: "definition",
      question: "Parmi les propositions suivantes, laquelle est un droit de l'actionnaire ordinaire ?",
      shortAnswer: "Le droit de vote en assemblée générale.",
      explanation: "L'actionnaire ordinaire dispose du droit de vote en AG, du droit au dividende (si distribué) et d'une part de l'actif net en cas de liquidation. Il n'a pas de coupon garanti ni de priorité de remboursement.",
      front: "Parmi les propositions suivantes, laquelle est un droit de l'actionnaire ordinaire ?",
      back: "Le droit de vote en assemblée générale.",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "droits"],
      skills: ["definition"],
      tags: ["action"],
      choices: [
        "Le droit de vote en assemblée générale",
        "Un coupon fixe garanti chaque année",
        "La priorité de remboursement en cas de faillite",
        "Une garantie de versement de dividende",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-action-num-2",
      type: "formula",
      questionType: "quick-calculation",
      question: "Vous achetez 200 actions à 15 € et les revendez toutes à 22 €. Quelle est votre plus-value totale (en €) ?",
      shortAnswer: "1 400 €",
      formula: "Plus-value = (Prix de vente − Prix d'achat) × Nombre d'actions",
      example: "(22 − 15) × 200 = 7 × 200 = 1 400 €",
      answerMode: "numeric",
      expectedAnswer: 1400,
      answerUnit: "€",
      tolerance: 0.01,
      front: "Vous achetez 200 actions à 15 € et les revendez toutes à 22 €. Quelle est votre plus-value totale (en €) ?",
      back: "1 400 €",
      difficulty: 1,
      learningStage: 1,
      topics: ["action", "plus-value", "calcul"],
      skills: ["quick-calculation"],
      tags: ["action", "calcul"],
    },
  ],
};
