import type { Lesson } from "@/lib/types";

export const lessonMarcheSecondaire: Lesson = {
  id: "mf-found-l1-marche-secondaire",
  slug: "marche-secondaire",
  title: "Le marché secondaire",
  description: "Comprendre le rôle de la Bourse dans l'échange de titres existants",
  estimatedMinutes: 6,
  cards: [
    {
      id: "mf-found-l1-ms-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le marché secondaire ?",
      shortAnswer:
        "Le marché secondaire est le marché où des titres déjà émis s'échangent entre investisseurs.",
      explanation:
        "L'émetteur ne reçoit pas les fonds de ces échanges : l'argent va au vendeur. La Bourse est l'exemple le plus visible de marché secondaire.",
      front: "Qu'est-ce que le marché secondaire ?",
      back: "Le marché secondaire est le marché où des titres déjà émis s'échangent entre investisseurs.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-secondaire", "bourse", "liquidité"],
      skills: ["definition"],
      tags: ["marché secondaire", "bourse"],
    },
    {
      id: "mf-found-l1-ms-intuition",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi le marché secondaire apporte-t-il de la liquidité aux investisseurs ?",
      shortAnswer:
        "Parce qu'il permet aux investisseurs de revendre leurs titres sans attendre leur maturité ou un événement particulier.",
      explanation:
        "Sans marché secondaire, acheter une obligation à 10 ans signifierait rester bloqué pendant 10 ans. La possibilité de sortir rend les titres plus attractifs.",
      front: "Pourquoi le marché secondaire apporte-t-il de la liquidité aux investisseurs ?",
      back: "Parce qu'il permet aux investisseurs de revendre leurs titres sans attendre leur maturité ou un événement particulier.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-secondaire", "liquidité", "investisseurs"],
      skills: ["mechanism"],
      tags: ["liquidité", "marché secondaire"],
    },
    {
      id: "mf-found-l1-ms-example",
      type: "example",
      questionType: "mechanism",
      question: "Quand vous achetez une action Apple en bourse, Apple reçoit-elle votre argent ?",
      shortAnswer:
        "Non. Vous achetez l'action à un autre investisseur sur le marché secondaire.",
      explanation:
        "Apple a reçu des fonds lors de son émission primaire. Les échanges quotidiens entre investisseurs ne financent pas directement l'entreprise.",
      front: "Quand vous achetez une action Apple en bourse, Apple reçoit-elle votre argent ?",
      back: "Non. Vous achetez l'action à un autre investisseur sur le marché secondaire.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-secondaire", "action", "bourse"],
      skills: ["mechanism"],
      tags: ["Apple", "NYSE", "marché secondaire"],
    },
    {
      id: "mf-found-l1-ms-trap",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre marché primaire et marché secondaire ?",
      shortAnswer:
        "Le primaire sert à émettre de nouveaux titres et finance l'émetteur. Le secondaire sert à échanger des titres déjà émis entre investisseurs.",
      explanation:
        "Une IPO est primaire au moment de l'émission. Les échanges en bourse dès le premier jour de cotation sont secondaires.",
      commonMistake:
        "Penser qu'une entreprise reçoit de l'argent à chaque échange de ses actions en bourse.",
      front: "Quelle est la différence entre marché primaire et marché secondaire ?",
      back: "Le primaire sert à émettre de nouveaux titres et finance l'émetteur. Le secondaire sert à échanger des titres déjà émis entre investisseurs.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-primaire", "marché-secondaire", "émission"],
      skills: ["comparison"],
      tags: ["IPO", "marché primaire", "marché secondaire"],
    },
    {
      id: "mf-found-l1-ms-iq",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi le marché secondaire aide-t-il aussi le marché primaire ?",
      shortAnswer:
        "Parce que la liquidité du secondaire rassure les investisseurs, qui acceptent plus facilement d'acheter les titres à l'émission.",
      explanation:
        "Si les investisseurs savent qu'ils pourront revendre, ils demandent une prime d'illiquidité plus faible. Cela peut réduire le coût de financement des émetteurs.",
      front: "Quelle est l'utilité économique du marché secondaire si l'entreprise n'y reçoit aucun argent ?",
      back: "Parce que la liquidité du secondaire rassure les investisseurs, qui acceptent plus facilement d'acheter les titres à l'émission.",
      difficulty: 2,
      learningStage: 1,
      topics: ["marché-secondaire", "liquidité", "marché-primaire"],
      skills: ["mechanism"],
      tags: ["marché secondaire", "liquidité"],
    },
    {
      id: "mf-found-l1-ms-ma",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la price discovery ?",
      shortAnswer:
        "La price discovery est le processus par lequel les échanges de marché agrègent l'information pour former un prix.",
      explanation:
        "Sur le marché secondaire, chaque ordre d'achat ou de vente apporte une information. Le prix devient un signal visible pour les investisseurs et les émetteurs.",
      front: "Qu'est-ce que la price discovery ?",
      back: "La price discovery est le processus par lequel les échanges de marché agrègent l'information pour former un prix.",
      difficulty: 2,
      learningStage: 1,
      topics: ["marché-secondaire", "price-discovery", "prix"],
      skills: ["definition"],
      tags: ["marché secondaire", "liquidité"],
    },
    {
      id: "mf-found-l1-ms-tf-1",
      type: "definition",
      questionType: "true-false",
      question: "Sur le marché secondaire, chaque transaction rapporte de l'argent à l'entreprise émettrice du titre.",
      shortAnswer: "Faux. Sur le marché secondaire, les fonds vont du vendeur à l'acheteur. L'entreprise émettrice ne reçoit rien.",
      explanation: "L'entreprise a reçu des fonds uniquement lors de l'émission primaire. Les échanges quotidiens en bourse ne la financent pas directement.",
      correctBool: false,
      front: "Sur le marché secondaire, chaque transaction rapporte de l'argent à l'entreprise émettrice du titre.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-secondaire", "financement"],
      skills: ["mechanism"],
      tags: ["marché secondaire"],
    },
    {
      id: "mf-found-l1-ms-tf-2",
      type: "definition",
      questionType: "true-false",
      question: "Euronext Paris est un exemple de marché secondaire.",
      shortAnswer: "Vrai. Euronext Paris est une bourse où s'échangent des titres déjà émis entre investisseurs : c'est bien un marché secondaire.",
      explanation: "Les premières émissions (IPO, obligations) relèvent du marché primaire. Dès le premier jour de cotation, les échanges en bourse sont secondaires.",
      correctBool: true,
      front: "Euronext Paris est un exemple de marché secondaire.",
      back: "Vrai.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-secondaire", "bourse"],
      skills: ["definition"],
      tags: ["marché secondaire", "bourse"],
    },
    {
      id: "mf-found-l1-ms-tf-3",
      type: "definition",
      questionType: "true-false",
      question: "Sans marché secondaire, les obligations à long terme seraient moins attractives pour les investisseurs.",
      shortAnswer: "Vrai. La possibilité de revendre avant l'échéance est un avantage clé. Sans cette sortie possible, les investisseurs exigeraient des rendements bien plus élevés.",
      explanation: "Le marché secondaire réduit la prime d'illiquidité que les émetteurs doivent payer. En facilitant la revente, il diminue le coût de financement des entreprises et des États.",
      correctBool: true,
      front: "Sans marché secondaire, les obligations à long terme seraient moins attractives pour les investisseurs.",
      back: "Vrai.",
      difficulty: 2,
      learningStage: 1,
      topics: ["marché-secondaire", "liquidité", "obligation"],
      skills: ["mechanism"],
      tags: ["marché secondaire", "liquidité"],
    },
    {
      id: "mf-found-l1-ms-mcq-1",
      type: "definition",
      questionType: "definition",
      question: "Quelle est la principale fonction économique du marché secondaire ?",
      shortAnswer: "Assurer la liquidité en permettant aux investisseurs de revendre leurs titres avant leur maturité.",
      explanation: "Le marché secondaire n'est pas destiné à lever des fonds pour les émetteurs — c'est le rôle du primaire. Sa fonction est de donner de la liquidité aux titres déjà émis.",
      front: "Quelle est la principale fonction économique du marché secondaire ?",
      back: "Assurer la liquidité en permettant aux investisseurs de revendre leurs titres.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-secondaire", "liquidité"],
      skills: ["mechanism"],
      tags: ["marché secondaire"],
      choices: [
        "Assurer la liquidité en permettant aux investisseurs de revendre leurs titres",
        "Financer directement les entreprises et les États",
        "Fixer le taux directeur de la banque centrale",
        "Émettre de nouvelles actions lors d'introductions en bourse",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-ms-mcq-2",
      type: "definition",
      questionType: "mechanism",
      question: "Vous achetez une action Airbus sur Euronext Paris. Qui reçoit votre argent ?",
      shortAnswer: "Le vendeur de l'action — un autre investisseur. Airbus ne reçoit rien de cette transaction.",
      explanation: "Airbus a reçu des fonds lors de son introduction en bourse (marché primaire). Sur le marché secondaire, l'argent circule uniquement entre investisseurs.",
      front: "Vous achetez une action Airbus sur Euronext Paris. Qui reçoit votre argent ?",
      back: "Le vendeur — un autre investisseur. Airbus ne reçoit rien.",
      difficulty: 1,
      learningStage: 1,
      topics: ["marché-secondaire", "action"],
      skills: ["mechanism"],
      tags: ["marché secondaire"],
      choices: [
        "Le vendeur de l'action (un autre investisseur)",
        "Airbus (l'entreprise émettrice)",
        "Euronext (l'opérateur de la bourse)",
        "La Banque de France",
      ],
      correctIndex: 0,
    },
  ],
};
