import type { Lesson } from "@/lib/types";

export const lessonMarketCap: Lesson = {
  id: "mf-found-l1-market-cap",
  slug: "capitalisation-boursiere",
  title: "La capitalisation boursière",
  description: "Calculer et interpréter la market cap d'une entreprise",
  estimatedMinutes: 6,
  cards: [
    {
      id: "mf-found-l1-cap-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la capitalisation boursière ?",
      shortAnswer:
        "La capitalisation boursière est la valeur de marché des capitaux propres d'une entreprise cotée.",
      formula: "Capitalisation boursière = Cours de l'action × Nombre d'actions en circulation",
      explanation:
        "Elle varie en permanence avec le cours de bourse et ne tient pas compte directement de la dette de l'entreprise.",
      front: "Qu'est-ce que la capitalisation boursière ?",
      back: "La capitalisation boursière est la valeur de marché des capitaux propres d'une entreprise cotée.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "action", "valeur-de-marché"],
      skills: ["definition"],
      tags: ["market cap", "capitalisation"],
    },
    {
      id: "mf-found-l1-cap-formula",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une entreprise a 500 millions d'actions et un cours de 750 euros. Quelle est sa capitalisation boursière ?",
      shortAnswer:
        "Sa capitalisation boursière est de 375 milliards d'euros.",
      formula: "Market cap = Cours × Nombre d'actions",
      example: "750 × 500 000 000 = 375 000 000 000 euros.",
      front: "Une entreprise a 500 millions d'actions et un cours de 750 euros. Quelle est sa capitalisation boursière ?",
      back: "Sa capitalisation boursière est de 375 milliards d'euros.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "calcul", "action"],
      skills: ["quick-calculation"],
      tags: ["market cap", "LVMH", "calcul"],
    },
    {
      id: "mf-found-l1-cap-intuition",
      type: "definition",
      questionType: "comparison",
      question: "La capitalisation boursière est-elle la valeur intrinsèque d'une entreprise ?",
      shortAnswer:
        "Non. Elle reflète le prix auquel le marché valorise l'equity à un instant donné, pas nécessairement la valeur intrinsèque.",
      explanation:
        "Le marché peut surévaluer ou sous-évaluer une entreprise. La market cap est un point de départ d'analyse, pas une preuve de juste valeur.",
      front: "La capitalisation boursière est-elle la valeur intrinsèque d'une entreprise ?",
      back: "Non. Elle reflète le prix auquel le marché valorise l'equity à un instant donné, pas nécessairement la valeur intrinsèque.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "valorisation", "prix-de-marché"],
      skills: ["comparison"],
      tags: ["valorisation", "market cap"],
    },
    {
      id: "mf-found-l1-cap-iq",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre capitalisation boursière et Enterprise Value ?",
      shortAnswer:
        "La market cap mesure la valeur de l'equity. L'Enterprise Value mesure la valeur totale de l'entreprise en ajoutant la dette nette.",
      formula: "EV = Market cap + Dette financière nette",
      explanation:
        "L'EV est souvent plus pertinente pour comparer des entreprises avec des structures de financement différentes.",
      front: "Quelle est la différence entre capitalisation boursière et Enterprise Value ?",
      back: "La market cap mesure la valeur de l'equity. L'Enterprise Value mesure la valeur totale de l'entreprise en ajoutant la dette nette.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "enterprise-value", "dette"],
      skills: ["comparison"],
      tags: ["market cap"],
    },
    {
      id: "mf-found-l1-cap-ma",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le free float ?",
      shortAnswer:
        "Le free float est la part des actions réellement disponible à l'échange sur le marché.",
      explanation:
        "Il exclut notamment les blocs détenus durablement par fondateurs, États ou actionnaires de contrôle. Un free float faible peut amplifier les mouvements de prix.",
      front: "Qu'est-ce que le free float ?",
      back: "Le free float est la part des actions réellement disponible à l'échange sur le marché.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "free-float", "liquidité"],
      skills: ["definition"],
      tags: ["market cap", "enterprise value", "EV"],
    },
    {
      id: "mf-found-l1-cap-ev-calculation",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une entreprise a 100 M€ de market cap, 200 M€ de dette et 50 M€ de trésorerie. Quelle est son Enterprise Value ?",
      shortAnswer:
        "Son Enterprise Value est de 250 M€.",
      formula: "EV = Market cap + Dette - Trésorerie",
      example: "100 + 200 - 50 = 250 M€.",
      front: "Une entreprise a 100 M€ de market cap, 200 M€ de dette et 50 M€ de trésorerie. Quelle est son Enterprise Value ?",
      back: "Son Enterprise Value est de 250 M€.",
      difficulty: 1,
      learningStage: 1,
      topics: ["enterprise-value", "capitalisation", "calcul"],
      skills: ["quick-calculation"],
      tags: ["enterprise value", "EV", "calcul"],
    },
    {
      id: "mf-found-l1-cap-tf-1",
      type: "definition",
      questionType: "true-false",
      question: "La capitalisation boursière d'une entreprise représente la valeur totale de ses actifs (usines, brevets, stocks…).",
      shortAnswer: "Faux. La market cap représente la valeur de marché des capitaux propres, pas des actifs. Les actifs sont financés à la fois par la dette et les capitaux propres.",
      explanation: "Pour estimer la valeur totale des actifs, on utilise l'Enterprise Value (EV = market cap + dette nette), qui tient compte de la structure de financement.",
      correctBool: false,
      front: "La capitalisation boursière d'une entreprise représente la valeur totale de ses actifs.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "actifs", "equity"],
      skills: ["definition"],
      tags: ["market cap", "capitalisation"],
    },
    {
      id: "mf-found-l1-cap-tf-2",
      type: "definition",
      questionType: "true-false",
      question: "L'Enterprise Value (EV) est toujours supérieure à la capitalisation boursière.",
      shortAnswer: "Faux. Si la trésorerie dépasse la dette financière (dette nette négative), l'EV est inférieure à la market cap.",
      explanation: "EV = Market cap + Dette nette. Si une entreprise a 500 M€ de market cap, 100 M€ de dette et 300 M€ de trésorerie, sa dette nette est −200 M€ et son EV = 300 M€ < market cap.",
      correctBool: false,
      front: "L'Enterprise Value (EV) est toujours supérieure à la capitalisation boursière.",
      back: "Faux.",
      difficulty: 2,
      learningStage: 1,
      topics: ["enterprise-value", "capitalisation", "trésorerie"],
      skills: ["comparison"],
      tags: ["market cap", "enterprise value"],
    },
    {
      id: "mf-found-l1-cap-tf-3",
      type: "definition",
      questionType: "true-false",
      question: "Une action dont le cours unitaire est de 500 € appartient nécessairement à une entreprise plus grande qu'une action à 10 €.",
      shortAnswer: "Faux. La taille d'une entreprise se mesure à sa capitalisation boursière (cours × nombre d'actions), pas au prix unitaire de l'action.",
      explanation: "Une action à 10 € avec 10 milliards d'actions représente une market cap de 100 Mds €. Une action à 500 € avec 1 million d'actions ne vaut que 500 M€.",
      correctBool: false,
      front: "Une action dont le cours unitaire est de 500 € appartient nécessairement à une entreprise plus grande qu'une action à 10 €.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "cours", "action"],
      skills: ["definition"],
      tags: ["market cap", "capitalisation"],
    },
    {
      id: "mf-found-l1-cap-mcq-1",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le free float d'une action ?",
      shortAnswer: "La part des actions réellement disponible à l'échange sur le marché (hors blocs détenus par les actionnaires de contrôle).",
      explanation: "Un free float faible signifie que peu d'actions circulent librement : cela réduit la liquidité et peut amplifier les mouvements de cours lors de gros ordres.",
      front: "Qu'est-ce que le free float d'une action ?",
      back: "La part des actions disponibles aux échanges de marché, hors blocs de contrôle.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "free-float", "liquidité"],
      skills: ["definition"],
      tags: ["market cap", "free float"],
      choices: [
        "La part des actions disponibles aux échanges de marché",
        "Le nombre total d'actions émises par l'entreprise",
        "La valeur comptable des capitaux propres au bilan",
        "La part du bénéfice non distribué aux actionnaires",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-cap-num-1",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une entreprise a 400 millions d'actions en circulation et un cours de 25 €. Quelle est sa capitalisation boursière en milliards d'euros ?",
      shortAnswer: "10 Mds €",
      formula: "Market cap = Cours × Nombre d'actions",
      example: "25 × 400 000 000 = 10 000 000 000 € = 10 Mds €",
      answerMode: "numeric",
      expectedAnswer: 10,
      answerUnit: "Mds €",
      tolerance: 0.01,
      front: "Une entreprise a 400 millions d'actions en circulation et un cours de 25 €. Quelle est sa capitalisation boursière en milliards d'euros ?",
      back: "10 Mds €",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "calcul", "action"],
      skills: ["quick-calculation"],
      tags: ["market cap", "calcul"],
    },
    {
      id: "mf-found-l1-cap-num-2",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une entreprise a une market cap de 600 M€, une dette financière de 250 M€ et une trésorerie de 50 M€. Quelle est son Enterprise Value (en M€) ?",
      shortAnswer: "800 M€",
      formula: "EV = Market cap + Dette financière − Trésorerie",
      example: "600 + 250 − 50 = 800 M€",
      answerMode: "numeric",
      expectedAnswer: 800,
      answerUnit: "M€",
      tolerance: 0.01,
      front: "Une entreprise a une market cap de 600 M€, une dette financière de 250 M€ et une trésorerie de 50 M€. Quelle est son Enterprise Value (en M€) ?",
      back: "800 M€",
      difficulty: 1,
      learningStage: 1,
      topics: ["enterprise-value", "capitalisation", "calcul"],
      skills: ["quick-calculation"],
      tags: ["enterprise value", "EV", "calcul"],
    },
  ],
};
