import type { Lesson } from "@/lib/types";

export const lessonMarketCap: Lesson = {
  id: "mf-found-l1-market-cap",
  slug: "capitalisation-boursiere",
  title: "La capitalisation boursière",
  description: "Calculer et interpréter la market cap d'une entreprise",
  estimatedMinutes: 6,
  cards: [
    {
      id: "mf-found-l1-cap-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la capitalisation boursière ?",
      shortAnswer:
        "La capitalisation boursière est la valeur de marché des capitaux propres d'une entreprise cotée.",
      formula: "Capitalisation boursière = Cours de l'action × Nombre d'actions en circulation",
      explanation:
        "Elle varie en permanence avec le cours de bourse et ne tient pas compte directement de la dette de l'entreprise.",
      front: "Qu'est-ce que la capitalisation boursière ?",
      back: "La capitalisation boursière est la valeur de marché des capitaux propres d'une entreprise cotée.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "action", "valeur-de-marché"],
      skills: ["definition"],
      tags: ["market cap", "capitalisation"],
    },
    {
      id: "mf-found-l1-cap-formula",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une entreprise a 500 millions d'actions et un cours de 750 euros. Quelle est sa capitalisation boursière ?",
      shortAnswer:
        "Sa capitalisation boursière est de 375 milliards d'euros.",
      formula: "Market cap = Cours × Nombre d'actions",
      example: "750 × 500 000 000 = 375 000 000 000 euros.",
      front: "Une entreprise a 500 millions d'actions et un cours de 750 euros. Quelle est sa capitalisation boursière ?",
      back: "Sa capitalisation boursière est de 375 milliards d'euros.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "calcul", "action"],
      skills: ["quick-calculation"],
      tags: ["market cap", "LVMH", "calcul"],
    },
    {
      id: "mf-found-l1-cap-intuition",
      type: "definition",
      questionType: "comparison",
      question: "La capitalisation boursière est-elle la valeur intrinsèque d'une entreprise ?",
      shortAnswer:
        "Non. Elle reflète le prix auquel le marché valorise l'equity à un instant donné, pas nécessairement la valeur intrinsèque.",
      explanation:
        "Le marché peut surévaluer ou sous-évaluer une entreprise. La market cap est un point de départ d'analyse, pas une preuve de juste valeur.",
      front: "La capitalisation boursière est-elle la valeur intrinsèque d'une entreprise ?",
      back: "Non. Elle reflète le prix auquel le marché valorise l'equity à un instant donné, pas nécessairement la valeur intrinsèque.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "valorisation", "prix-de-marché"],
      skills: ["comparison"],
      tags: ["valorisation", "market cap"],
    },
    {
      id: "mf-found-l1-cap-iq",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre capitalisation boursière et Enterprise Value ?",
      shortAnswer:
        "La market cap mesure la valeur de l'equity. L'Enterprise Value mesure la valeur totale de l'entreprise en ajoutant la dette nette.",
      formula: "EV = Market cap + Dette financière nette",
      explanation:
        "L'EV est souvent plus pertinente pour comparer des entreprises avec des structures de financement différentes.",
      front: "Quelle est la différence entre capitalisation boursière et Enterprise Value ?",
      back: "La market cap mesure la valeur de l'equity. L'Enterprise Value mesure la valeur totale de l'entreprise en ajoutant la dette nette.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "enterprise-value", "dette"],
      skills: ["comparison"],
      tags: ["market cap"],
    },
    {
      id: "mf-found-l1-cap-ma",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le free float ?",
      shortAnswer:
        "Le free float est la part des actions réellement disponible à l'échange sur le marché.",
      explanation:
        "Il exclut notamment les blocs détenus durablement par fondateurs, États ou actionnaires de contrôle. Un free float faible peut amplifier les mouvements de prix.",
      front: "Qu'est-ce que le free float ?",
      back: "Le free float est la part des actions réellement disponible à l'échange sur le marché.",
      difficulty: 1,
      learningStage: 1,
      topics: ["capitalisation", "free-float", "liquidité"],
      skills: ["definition"],
      tags: ["market cap", "enterprise value", "EV"],
    },
    {
      id: "mf-found-l1-cap-ev-calculation",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une entreprise a 100 M€ de market cap, 200 M€ de dette et 50 M€ de trésorerie. Quelle est son Enterprise Value ?",
      shortAnswer:
        "Son Enterprise Value est de 250 M€.",
      formula: "EV = Market cap + Dette - Trésorerie",
      example: "100 + 200 - 50 = 250 M€.",
      front: "Une entreprise a 100 M€ de market cap, 200 M€ de dette et 50 M€ de trésorerie. Quelle est son Enterprise Value ?",
      back: "Son Enterprise Value est de 250 M€.",
      difficulty: 1,
      learningStage: 1,
      topics: ["enterprise-value", "capitalisation", "calcul"],
      skills: ["quick-calculation"],
      tags: ["enterprise value", "EV", "calcul"],
    },
  ],
};
