import type { Lesson } from "@/lib/types";

export const lessonObligation: Lesson = {
  id: "mf-found-l1-obligation",
  slug: "obligation",
  title: "L'obligation",
  description: "Comprendre ce qu'est une obligation et comment elle fonctionne",
  estimatedMinutes: 8,
  cards: [
    {
      id: "mf-found-l1-oblig-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'une obligation ?",
      shortAnswer:
        "Une obligation est un titre de dette : l'investisseur prête de l'argent à un émetteur, qui verse des coupons et rembourse le principal à maturité.",
      explanation:
        "L'émetteur peut être un État, une entreprise ou une institution financière. L'investisseur est créancier, pas propriétaire.",
      front: "Qu'est-ce qu'une obligation ?",
      back: "Une obligation est un titre de dette : l'investisseur prête de l'argent à un émetteur, qui verse des coupons et rembourse le principal à maturité.",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "dette", "coupon"],
      skills: ["definition"],
      tags: ["obligation", "dette"],
    },
    {
      id: "mf-found-l1-oblig-intuition",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi une entreprise émet-elle une obligation plutôt que de prendre un prêt bancaire ?",
      shortAnswer:
        "Elle peut accéder à davantage d'investisseurs, emprunter des montants plus élevés et choisir des maturités parfois plus longues.",
      explanation:
        "Une obligation est négociable sur le marché secondaire, ce qui rend l'investissement plus flexible pour les investisseurs qu'un prêt bancaire classique.",
      front: "Pourquoi une entreprise émet-elle une obligation plutôt que de prendre un prêt bancaire ?",
      back: "Elle peut accéder à davantage d'investisseurs, emprunter des montants plus élevés et choisir des maturités parfois plus longues.",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "marché-obligataire", "financement"],
      skills: ["mechanism"],
      tags: ["obligation", "financement"],
    },
    {
      id: "mf-found-l1-oblig-formula",
      type: "formula",
      questionType: "definition",
      question: "Quels sont les principaux composants d'une obligation ?",
      shortAnswer:
        "Les composants clés sont la valeur nominale, le coupon, la maturité et le prix de marché.",
      explanation:
        "La valeur nominale est le montant remboursé à maturité. Le coupon est l'intérêt périodique. Le prix de marché peut varier avant la maturité.",
      example:
        "Pour une obligation de nominal 1 000 euros avec coupon 3 %, l'investisseur reçoit 30 euros par an.",
      front: "Quels sont les principaux composants d'une obligation ?",
      back: "Les composants clés sont la valeur nominale, le coupon, la maturité et le prix de marché.",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "coupon", "maturité"],
      skills: ["definition"],
      tags: ["obligation", "coupon"],
    },
    {
      id: "mf-found-l1-oblig-example",
      type: "example",
      questionType: "quick-calculation",
      question: "Une obligation de nominal 100 000 euros paie un coupon de 3 %. Quel coupon annuel reçoit l'investisseur ?",
      shortAnswer:
        "L'investisseur reçoit 3 000 euros par an.",
      formula: "Coupon annuel = Nominal × Taux de coupon",
      example: "100 000 × 3 % = 3 000 euros.",
      front: "Une obligation de nominal 100 000 euros paie un coupon de 3 %. Quel coupon annuel reçoit l'investisseur ?",
      back: "L'investisseur reçoit 3 000 euros par an.",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "coupon", "calcul"],
      skills: ["quick-calculation"],
      tags: ["obligation", "coupon"],
    },
    {
      id: "mf-found-l1-oblig-trap",
      type: "definition",
      questionType: "mechanism",
      question: "Que se passe-t-il au prix d'une obligation existante quand les taux montent ?",
      shortAnswer:
        "Son prix baisse généralement, car les nouvelles obligations offrent des coupons ou rendements plus attractifs.",
      explanation:
        "Le prix de l'obligation existante doit baisser pour que son rendement effectif redevienne compétitif avec les nouvelles émissions.",
      commonMistake:
        "Ne pas confondre coupon fixe et rendement de marché : le coupon ne change pas, mais le prix peut changer.",
      front: "Que se passe-t-il au prix d'une obligation existante quand les taux montent ?",
      back: "Son prix baisse généralement, car les nouvelles obligations offrent des coupons ou rendements plus attractifs.",
      difficulty: 2,
      learningStage: 1,
      topics: ["obligation", "taux", "prix"],
      skills: ["mechanism"],
      tags: ["obligation", "taux", "prix"],
    },
    {
      id: "mf-found-l1-oblig-iq",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi les prix des obligations baissent-ils quand les taux montent ?",
      shortAnswer:
        "Parce que les flux fixes de l'obligation sont actualisés à un taux plus élevé, ce qui réduit leur valeur actuelle.",
      explanation:
        "Il y a aussi une logique d'arbitrage : si le marché offre maintenant 4 %, une obligation existante à 2 % doit baisser de prix pour offrir un rendement comparable.",
      front: "Pourquoi les prix des obligations baissent-ils quand les taux montent ?",
      back: "Parce que les flux fixes de l'obligation sont actualisés à un taux plus élevé, ce qui réduit leur valeur actuelle.",
      difficulty: 2,
      learningStage: 1,
      topics: ["obligation", "taux", "actualisation"],
      skills: ["mechanism"],
      tags: ["obligation", "taux", "prix"],
    },
    {
      id: "mf-found-l1-oblig-ma",
      type: "definition",
      questionType: "definition",
      question: "Que mesure la duration d'une obligation ?",
      shortAnswer:
        "La duration mesure la sensibilité approximative du prix d'une obligation à une variation des taux.",
      explanation:
        "Une duration de 7 signifie qu'une hausse de taux de 1 point peut faire baisser le prix d'environ 7 %, toutes choses égales par ailleurs.",
      front: "Que mesure la duration d'une obligation ?",
      back: "La duration mesure la sensibilité approximative du prix d'une obligation à une variation des taux.",
      difficulty: 2,
      learningStage: 1,
      topics: ["obligation", "duration", "taux"],
      skills: ["definition"],
      tags: ["obligation", "taux", "duration"],
    },
    {
      id: "mf-found-l1-oblig-tf-1",
      type: "definition",
      questionType: "true-false",
      question: "Quand les taux d'intérêt augmentent, le prix des obligations à coupon fixe déjà émises augmente également.",
      shortAnswer: "Faux. Quand les taux montent, le prix des obligations existantes baisse pour que leur rendement reste compétitif.",
      explanation: "Les flux futurs fixes de l'obligation sont actualisés à un taux plus élevé, ce qui réduit leur valeur actuelle. Un investisseur qui veut vendre son obligation doit baisser son prix pour attirer des acheteurs.",
      correctBool: false,
      front: "Quand les taux d'intérêt augmentent, le prix des obligations à coupon fixe déjà émises augmente également.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "taux", "prix"],
      skills: ["mechanism"],
      tags: ["obligation", "taux"],
    },
    {
      id: "mf-found-l1-oblig-tf-2",
      type: "definition",
      questionType: "true-false",
      question: "Une obligation à coupon zéro ne verse aucun intérêt avant la date de remboursement.",
      shortAnswer: "Vrai. L'obligation zéro-coupon est émise à un prix décoté et remboursée à sa valeur nominale à maturité — la différence constitue le rendement.",
      explanation: "Par exemple, une obligation zéro-coupon de nominal 1 000 € émise à 750 € pour 5 ans offre un rendement actuariel sans aucun flux intermédiaire.",
      correctBool: true,
      front: "Une obligation à coupon zéro ne verse aucun intérêt avant la date de remboursement.",
      back: "Vrai.",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "coupon", "zéro-coupon"],
      skills: ["definition"],
      tags: ["obligation", "coupon"],
    },
    {
      id: "mf-found-l1-oblig-tf-3",
      type: "definition",
      questionType: "true-false",
      question: "L'investisseur qui achète une obligation devient propriétaire d'une fraction du capital de l'émetteur.",
      shortAnswer: "Faux. Il devient créancier, pas actionnaire. Il a un droit de remboursement prioritaire, mais ne détient aucune part de propriété.",
      explanation: "C'est la différence fondamentale entre dette et capital : l'obligataire prête, l'actionnaire investit en capital. En cas de faillite, l'obligataire est remboursé avant l'actionnaire.",
      correctBool: false,
      front: "L'investisseur qui achète une obligation devient propriétaire d'une fraction du capital de l'émetteur.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "dette", "capital"],
      skills: ["definition"],
      tags: ["obligation", "dette"],
    },
    {
      id: "mf-found-l1-oblig-mcq-1",
      type: "definition",
      questionType: "definition",
      question: "Quel terme désigne le montant remboursé par l'émetteur à l'investisseur à l'échéance d'une obligation ?",
      shortAnswer: "La valeur nominale (ou principal).",
      explanation: "La valeur nominale est le montant de référence sur lequel le coupon est calculé. Elle est remboursée intégralement à maturité, indépendamment du prix auquel l'obligation a été échangée sur le marché.",
      front: "Quel terme désigne le montant remboursé par l'émetteur à l'investisseur à l'échéance d'une obligation ?",
      back: "La valeur nominale (ou principal).",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "nominal", "remboursement"],
      skills: ["definition"],
      tags: ["obligation", "coupon"],
      choices: [
        "La valeur nominale (principal)",
        "Le coupon final majoré",
        "Le prix de marché à maturité",
        "La prime de remboursement",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-oblig-mcq-2",
      type: "definition",
      questionType: "definition",
      question: "Que mesure principalement la duration d'une obligation ?",
      shortAnswer: "La sensibilité du prix de l'obligation à une variation des taux d'intérêt.",
      explanation: "Une duration de 5 indique qu'une hausse de taux de 1 % entraîne une baisse de prix d'environ 5 %. Plus la duration est élevée, plus l'obligation est sensible aux taux.",
      front: "Que mesure principalement la duration d'une obligation ?",
      back: "La sensibilité du prix de l'obligation à une variation des taux d'intérêt.",
      difficulty: 2,
      learningStage: 1,
      topics: ["obligation", "duration", "taux"],
      skills: ["definition"],
      tags: ["obligation", "duration"],
      choices: [
        "La sensibilité du prix aux variations de taux d'intérêt",
        "La durée totale restante jusqu'à maturité",
        "Le montant total des coupons versés sur la vie de l'obligation",
        "Le risque de défaut de l'émetteur",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-oblig-num-1",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une obligation a une valeur nominale de 10 000 € et un taux de coupon de 4 %. Quel est le montant du coupon annuel versé à l'investisseur (en €) ?",
      shortAnswer: "400 €",
      formula: "Coupon annuel = Valeur nominale × Taux de coupon",
      example: "10 000 × 4 % = 10 000 × 0,04 = 400 €",
      answerMode: "numeric",
      expectedAnswer: 400,
      answerUnit: "€",
      tolerance: 0.01,
      front: "Une obligation a une valeur nominale de 10 000 € et un taux de coupon de 4 %. Quel est le montant du coupon annuel versé à l'investisseur (en €) ?",
      back: "400 €",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "coupon", "calcul"],
      skills: ["quick-calculation"],
      tags: ["obligation", "calcul"],
    },
    {
      id: "mf-found-l1-oblig-num-2",
      type: "formula",
      questionType: "quick-calculation",
      question: "Une obligation verse un coupon annuel de 60 € et a une valeur nominale de 1 000 €. Quel est son taux de coupon (en %) ?",
      shortAnswer: "6 %",
      formula: "Taux de coupon = Coupon annuel / Valeur nominale × 100",
      example: "60 / 1 000 × 100 = 6 %",
      answerMode: "numeric",
      expectedAnswer: 6,
      answerUnit: "%",
      tolerance: 0.01,
      front: "Une obligation verse un coupon annuel de 60 € et a une valeur nominale de 1 000 €. Quel est son taux de coupon (en %) ?",
      back: "6 %",
      difficulty: 1,
      learningStage: 1,
      topics: ["obligation", "coupon", "calcul"],
      skills: ["quick-calculation"],
      tags: ["obligation", "calcul"],
    },
  ],
};
