import type { Lesson } from "@/lib/types";

export const lessonRendement: Lesson = {
  id: "mf-found-l1-rendement",
  slug: "rendement",
  title: "Le rendement",
  description: "Calculer et interpréter le rendement d'un investissement",
  estimatedMinutes: 7,
  cards: [
    {
      id: "mf-found-l1-rend-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le rendement d'un investissement ?",
      shortAnswer:
        "Le rendement est le gain total d'un investissement exprimé en pourcentage du capital investi.",
      explanation:
        "Il peut inclure à la fois les revenus reçus, comme dividendes ou coupons, et la plus-value ou moins-value sur le prix.",
      front: "Qu'est-ce que le rendement ?",
      back: "Le rendement est le gain total d'un investissement exprimé en pourcentage du capital investi.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "performance", "investissement"],
      skills: ["definition"],
      tags: ["rendement"],
    },
    {
      id: "mf-found-l1-rend-formula",
      type: "formula",
      questionType: "formula",
      question: "Quelle est la formule du rendement simple ?",
      shortAnswer:
        "Le rendement simple rapporte le gain total au capital investi.",
      formula: "Rendement = (Prix final - Prix initial + Revenus) / Prix initial",
      example: "Achat 100, vente 110, dividende 3 : rendement = (110 - 100 + 3) / 100 = 13 %.",
      front: "Quelle est la formule du rendement simple ?",
      back: "Rendement = (Prix final - Prix initial + Revenus) / Prix initial.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "calcul", "performance"],
      skills: ["formula"],
      tags: ["rendement", "calcul"],
    },
    {
      id: "mf-found-l1-rend-intuition",
      type: "definition",
      questionType: "mechanism",
      question: "Pourquoi rendement attendu et risque sont-ils indissociables ?",
      shortAnswer:
        "Parce qu'un investisseur exige généralement un rendement plus élevé pour accepter un risque plus élevé.",
      explanation:
        "L'écart de rendement demandé pour porter un risque supplémentaire s'appelle une prime de risque.",
      example:
        "Une obligation d'État solide à 3 % et une obligation fragile à 8 % ne rémunèrent pas le même niveau de risque.",
      front: "Pourquoi rendement attendu et risque sont-ils indissociables ?",
      back: "Parce qu'un investisseur exige généralement un rendement plus élevé pour accepter un risque plus élevé.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "risque", "prime-de-risque"],
      skills: ["mechanism"],
      tags: ["rendement", "risque", "prime"],
    },
    {
      id: "mf-found-l1-rend-trap",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre rendement brut, rendement net et rendement réel ?",
      shortAnswer:
        "Le rendement brut ignore frais et fiscalité. Le rendement net les déduit. Le rendement réel déduit aussi l'inflation.",
      explanation:
        "Un rendement nominal positif peut être faible, voire négatif, en pouvoir d'achat si l'inflation est élevée.",
      commonMistake:
        "Comparer deux performances sans préciser si elles sont brutes ou nettes, nominales ou réelles.",
      front: "Quelle est la différence entre rendement brut, rendement net et rendement réel ?",
      back: "Le rendement brut ignore frais et fiscalité. Le rendement net les déduit. Le rendement réel déduit aussi l'inflation.",
      difficulty: 2,
      learningStage: 1,
      topics: ["rendement", "inflation", "frais"],
      skills: ["comparison"],
      tags: ["rendement", "fiscalité", "inflation"],
    },
    {
      id: "mf-found-l1-rend-iq",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le taux sans risque ?",
      shortAnswer:
        "Le taux sans risque est le rendement théorique d'un actif sans risque de défaut sur une maturité donnée.",
      explanation:
        "En pratique, on l'approche avec les obligations d'État les plus sûres, par exemple le T-bill ou le Treasury américain, ou le Bund allemand en euros.",
      front: "Qu'est-ce que le taux sans risque ?",
      back: "Le taux sans risque est le rendement théorique d'un actif sans risque de défaut sur une maturité donnée.",
      difficulty: 2,
      learningStage: 1,
      topics: ["rendement", "taux", "taux-sans-risque"],
      skills: ["definition"],
      tags: ["rendement", "taux", "CAPM"],
    },
    {
      id: "mf-found-l1-rend-ma",
      type: "definition",
      questionType: "comparison",
      question: "Le taux sans risque signifie-t-il vraiment qu'il n'y a aucun risque ?",
      shortAnswer:
        "Non. Il signifie surtout absence de risque de défaut dans l'approximation utilisée, mais il peut rester un risque de taux ou d'inflation.",
      explanation:
        "Une obligation d'État très sûre peut perdre de la valeur si les taux montent avant sa maturité.",
      front: "Le taux sans risque signifie-t-il vraiment qu'il n'y a aucun risque ?",
      back: "Non. Il signifie surtout absence de risque de défaut dans l'approximation utilisée, mais il peut rester un risque de taux ou d'inflation.",
      difficulty: 2,
      learningStage: 1,
      topics: ["rendement", "taux-sans-risque", "risque-de-taux"],
      skills: ["comparison"],
      tags: ["rendement", "taux", "CAPM"],
    },
    {
      id: "mf-found-l1-rend-tf-1",
      type: "definition",
      questionType: "true-false",
      question: "Un rendement nominal positif garantit que le pouvoir d'achat de l'investisseur a augmenté.",
      shortAnswer: "Faux. Si l'inflation est supérieure au rendement nominal, le rendement réel est négatif et le pouvoir d'achat diminue.",
      explanation: "Rendement réel ≈ Rendement nominal − Inflation. Un rendement nominal de 2 % avec une inflation de 4 % donne un rendement réel de −2 %.",
      correctBool: false,
      front: "Un rendement nominal positif garantit que le pouvoir d'achat de l'investisseur a augmenté.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "inflation", "pouvoir-achat"],
      skills: ["comparison"],
      tags: ["rendement", "inflation"],
    },
    {
      id: "mf-found-l1-rend-tf-2",
      type: "definition",
      questionType: "true-false",
      question: "Plus un investissement est risqué, plus les investisseurs exigent un rendement attendu élevé.",
      shortAnswer: "Vrai. C'est le principe de la prime de risque : un investisseur rationnel demande une compensation pour accepter davantage d'incertitude.",
      explanation: "Cette prime de risque explique pourquoi les actions offrent historiquement un rendement supérieur aux obligations d'État sur le long terme.",
      correctBool: true,
      front: "Plus un investissement est risqué, plus les investisseurs exigent un rendement attendu élevé.",
      back: "Vrai.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "risque", "prime-de-risque"],
      skills: ["mechanism"],
      tags: ["rendement", "risque"],
    },
    {
      id: "mf-found-l1-rend-tf-3",
      type: "definition",
      questionType: "true-false",
      question: "Le rendement brut et le rendement net d'un investissement sont toujours identiques.",
      shortAnswer: "Faux. Le rendement net déduit les frais et la fiscalité du rendement brut. Ces charges peuvent réduire significativement la performance réelle.",
      explanation: "Exemple : un fonds affichant 8 % brut peut délivrer seulement 5,6 % net après 2 % de frais de gestion et prélèvements sociaux.",
      correctBool: false,
      front: "Le rendement brut et le rendement net d'un investissement sont toujours identiques.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "frais", "fiscalité"],
      skills: ["comparison"],
      tags: ["rendement", "fiscalité"],
    },
    {
      id: "mf-found-l1-rend-mcq-1",
      type: "definition",
      questionType: "definition",
      question: "Quel instrument financier est généralement utilisé comme approximation du taux sans risque en zone euro ?",
      shortAnswer: "L'obligation d'État allemande (Bund) à 10 ans.",
      explanation: "L'Allemagne est considérée comme l'emprunteur le plus sûr de la zone euro. Le Bund 10 ans sert de référence pour calculer les primes de risque des autres actifs en euros.",
      front: "Quel instrument financier est généralement utilisé comme approximation du taux sans risque en zone euro ?",
      back: "L'obligation d'État allemande (Bund) à 10 ans.",
      difficulty: 2,
      learningStage: 1,
      topics: ["rendement", "taux-sans-risque", "obligation"],
      skills: ["market-culture"],
      tags: ["rendement", "taux", "CAPM"],
      choices: [
        "L'obligation d'État allemande (Bund) à 10 ans",
        "L'OAT française à 10 ans",
        "L'Euribor 3 mois",
        "Le taux de dépôt de la BCE",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-rend-mcq-2",
      type: "definition",
      questionType: "comparison",
      question: "Parmi les propositions suivantes, laquelle décrit correctement le rendement réel d'un investissement ?",
      shortAnswer: "Le rendement réel est le rendement nominal diminué de l'inflation.",
      explanation: "C'est la mesure du gain en pouvoir d'achat. Un rendement nominal de 5 % avec une inflation de 3 % donne un rendement réel d'environ 2 %.",
      front: "Parmi les propositions suivantes, laquelle décrit correctement le rendement réel d'un investissement ?",
      back: "Le rendement réel est le rendement nominal diminué de l'inflation.",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "inflation", "réel"],
      skills: ["comparison"],
      tags: ["rendement", "inflation"],
      choices: [
        "Le rendement nominal diminué de l'inflation",
        "Le rendement brut avant déduction des frais",
        "Le rendement calculé après impôts uniquement",
        "Le rendement annualisé sur 10 ans",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-rend-num-1",
      type: "formula",
      questionType: "quick-calculation",
      question: "Un investisseur achète une action à 80 €, reçoit un dividende de 4 € et revend l'action à 96 €. Quel est son rendement simple (en %) ?",
      shortAnswer: "25 %",
      formula: "Rendement = (Prix final − Prix initial + Revenus) / Prix initial × 100",
      example: "(96 − 80 + 4) / 80 × 100 = 20 / 80 × 100 = 25 %",
      answerMode: "numeric",
      expectedAnswer: 25,
      answerUnit: "%",
      tolerance: 0.01,
      front: "Un investisseur achète une action à 80 €, reçoit un dividende de 4 € et revend l'action à 96 €. Quel est son rendement simple (en %) ?",
      back: "25 %",
      difficulty: 1,
      learningStage: 1,
      topics: ["rendement", "calcul", "dividende"],
      skills: ["quick-calculation"],
      tags: ["rendement", "calcul"],
    },
  ],
};
