import type { Lesson } from "@/lib/types";

export const lessonRisque: Lesson = {
  id: "mf-found-l1-risque",
  slug: "risque",
  title: "Le risque",
  description: "Identifier et comprendre les différents types de risques financiers",
  estimatedMinutes: 7,
  cards: [
    {
      id: "mf-found-l1-risque-def",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le risque en finance ?",
      shortAnswer:
        "Le risque est la possibilité que le rendement réalisé diffère du rendement attendu.",
      explanation:
        "Il ne signifie pas seulement perte certaine : il mesure l'incertitude. On peut notamment parler de risque de marché, de crédit, de liquidité ou opérationnel.",
      front: "Qu'est-ce que le risque en finance ?",
      back: "Le risque est la possibilité que le rendement réalisé diffère du rendement attendu.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "rendement", "incertitude"],
      skills: ["definition"],
      tags: ["risque", "volatilité"],
    },
    {
      id: "mf-found-l1-risque-example",
      type: "example",
      questionType: "comparison",
      question: "Quels sont les quatre grands types de risques en finance de marché ?",
      shortAnswer:
        "Les grands types sont le risque de marché, le risque de crédit, le risque de liquidité et le risque opérationnel.",
      explanation:
        "Le risque de marché vient des mouvements de prix. Le crédit vient du défaut d'un émetteur. La liquidité vient de la difficulté à vendre. L'opérationnel vient d'erreurs, fraudes ou défaillances internes.",
      example:
        "Exemples : krach actions, défaut Lehman Brothers, actifs invendables en 2008, fraude Kerviel.",
      front: "Quels sont les quatre grands types de risques en finance de marché ?",
      back: "Les grands types sont le risque de marché, le risque de crédit, le risque de liquidité et le risque opérationnel.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "crédit", "liquidité"],
      skills: ["comparison"],
      tags: ["risque", "crédit", "liquidité"],
    },
    {
      id: "mf-found-l1-risque-intuition",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre risque et perte certaine ?",
      shortAnswer:
        "Le risque est une incertitude sur le résultat. Une perte certaine est déjà connue ou quasiment inévitable.",
      explanation:
        "Un actif risqué peut très bien produire une excellente performance. À l'inverse, un actif apparemment stable peut cacher un risque de défaut ou d'illiquidité.",
      commonMistake:
        "Assimiler tout risque à une perte alors que le risque mesure une distribution de résultats possibles.",
      front: "Quelle est la différence entre risque et perte certaine ?",
      back: "Le risque est une incertitude sur le résultat. Une perte certaine est déjà connue ou quasiment inévitable.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "incertitude", "perte"],
      skills: ["comparison"],
      tags: ["risque", "incertitude"],
    },
    {
      id: "mf-found-l1-risque-iq",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la volatilité ?",
      shortAnswer:
        "La volatilité mesure l'ampleur des variations de prix ou de rendement d'un actif sur une période.",
      explanation:
        "Elle est souvent calculée comme l'écart-type des rendements. Une volatilité élevée signifie que les résultats possibles sont plus dispersés.",
      front: "Qu'est-ce que la volatilité ?",
      back: "La volatilité mesure l'ampleur des variations de prix ou de rendement d'un actif sur une période.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "volatilité", "rendement"],
      skills: ["definition"],
      tags: ["risque"],
    },
    {
      id: "mf-found-l1-risque-ma",
      type: "definition",
      questionType: "mechanism",
      question: "Comment la diversification réduit-elle le risque d'un portefeuille ?",
      shortAnswer:
        "Elle réduit le risque spécifique en combinant des actifs dont les performances ne bougent pas parfaitement ensemble.",
      explanation:
        "La diversification ne supprime pas le risque de marché global, mais elle peut réduire l'impact d'un problème propre à une entreprise ou un secteur.",
      front: "Comment la diversification réduit-elle le risque d'un portefeuille ?",
      back: "Elle réduit le risque spécifique en combinant des actifs dont les performances ne bougent pas parfaitement ensemble.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "diversification", "portefeuille"],
      skills: ["mechanism"],
      tags: ["risque"],
    },
    {
      id: "mf-found-l1-risque-credit-market",
      type: "definition",
      questionType: "comparison",
      question: "Quelle est la différence entre risque de marché et risque de crédit ?",
      shortAnswer:
        "Le risque de marché vient des mouvements de prix. Le risque de crédit vient de la capacité d'un émetteur ou d'une contrepartie à payer.",
      explanation:
        "Une action qui baisse avec le marché illustre le risque de marché. Une obligation dont l'émetteur fait défaut illustre le risque de crédit.",
      front: "Quelle est la différence entre risque de marché et risque de crédit ?",
      back: "Le risque de marché vient des mouvements de prix. Le risque de crédit vient de la capacité d'un émetteur ou d'une contrepartie à payer.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "risque-de-marché", "risque-de-crédit"],
      skills: ["comparison"],
      tags: ["risque", "crédit"],
    },
    {
      id: "mf-found-l1-risque-tf-1",
      type: "definition",
      questionType: "true-false",
      question: "La volatilité d'un actif mesure la probabilité qu'il perde la totalité de sa valeur.",
      shortAnswer: "Faux. La volatilité mesure l'ampleur des variations de prix (écart-type des rendements), pas la probabilité de perte totale.",
      explanation: "Une action très volatile peut fortement monter ou baisser — elle n'est pas condamnée à valoir zéro. La perte totale relève plutôt du risque de crédit (faillite de l'émetteur).",
      correctBool: false,
      front: "La volatilité d'un actif mesure la probabilité qu'il perde la totalité de sa valeur.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "volatilité"],
      skills: ["definition"],
      tags: ["risque", "volatilité"],
    },
    {
      id: "mf-found-l1-risque-tf-2",
      type: "definition",
      questionType: "true-false",
      question: "La diversification d'un portefeuille permet d'éliminer complètement le risque.",
      shortAnswer: "Faux. La diversification élimine le risque spécifique (propre à chaque actif) mais pas le risque systématique (risque de marché global).",
      explanation: "Un choc macro comme une récession mondiale affecte tous les actifs en même temps : la diversification ne protège pas contre ce risque commun.",
      correctBool: false,
      front: "La diversification d'un portefeuille permet d'éliminer complètement le risque.",
      back: "Faux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "diversification", "risque-systématique"],
      skills: ["mechanism"],
      tags: ["risque", "diversification"],
    },
    {
      id: "mf-found-l1-risque-tf-3",
      type: "definition",
      questionType: "true-false",
      question: "Le risque de liquidité désigne la possibilité qu'un actif ne puisse pas être vendu rapidement à un prix raisonnable.",
      shortAnswer: "Vrai. C'est exactement la définition du risque de liquidité : l'impossibilité de sortir d'une position sans subir une forte décote.",
      explanation: "En 2008, certains actifs structurés réputés liquides sont devenus totalement invendables : leurs détenteurs ont été contraints de les garder ou de les vendre à des prix catastrophiques.",
      correctBool: true,
      front: "Le risque de liquidité désigne la possibilité qu'un actif ne puisse pas être vendu rapidement à un prix raisonnable.",
      back: "Vrai.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "liquidité"],
      skills: ["definition"],
      tags: ["risque", "liquidité"],
    },
    {
      id: "mf-found-l1-risque-mcq-1",
      type: "definition",
      questionType: "definition",
      question: "Lequel de ces événements illustre principalement un risque de crédit ?",
      shortAnswer: "La faillite d'un émetteur d'obligations qui ne peut plus rembourser ses dettes.",
      explanation: "Le risque de crédit est le risque qu'une contrepartie ne respecte pas ses engagements financiers. La faillite de Lehman Brothers en 2008 en est l'exemple emblématique.",
      front: "Lequel de ces événements illustre principalement un risque de crédit ?",
      back: "La faillite d'un émetteur d'obligations qui ne peut plus rembourser ses dettes.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "risque-de-crédit"],
      skills: ["definition"],
      tags: ["risque", "crédit"],
      choices: [
        "La faillite d'un émetteur d'obligations",
        "Un krach boursier affectant toutes les actions",
        "L'impossibilité de revendre rapidement un actif",
        "Une erreur dans un système de règlement",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-risque-mcq-2",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le risque systématique (ou risque de marché) ?",
      shortAnswer: "Un risque qui affecte l'ensemble du marché et ne peut pas être éliminé par la diversification.",
      explanation: "Le risque systématique est lié à des facteurs macroéconomiques globaux (taux, récession, crise géopolitique) qui touchent tous les actifs simultanément. Le risque spécifique, lui, est diversifiable.",
      front: "Qu'est-ce que le risque systématique (ou risque de marché) ?",
      back: "Un risque qui affecte l'ensemble du marché et ne peut pas être éliminé par la diversification.",
      difficulty: 1,
      learningStage: 1,
      topics: ["risque", "risque-systématique", "diversification"],
      skills: ["definition"],
      tags: ["risque"],
      choices: [
        "Un risque affectant tout le marché, non diversifiable",
        "Un risque propre à une seule entreprise, éliminable par diversification",
        "Le risque qu'un émetteur ne rembourse pas sa dette",
        "Le risque de ne pas pouvoir revendre un actif",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l1-risque-num-1",
      type: "formula",
      questionType: "quick-calculation",
      question: "Un actif a une valeur de 500 € et une volatilité annuelle de 20 %. Quel est l'écart-type annuel de sa valeur (en €) ?",
      shortAnswer: "100 €",
      formula: "Écart-type en valeur = Valeur × Volatilité",
      example: "500 × 20 % = 500 × 0,20 = 100 €",
      answerMode: "numeric",
      expectedAnswer: 100,
      answerUnit: "€",
      tolerance: 0.01,
      front: "Un actif a une valeur de 500 € et une volatilité annuelle de 20 %. Quel est l'écart-type annuel de sa valeur (en €) ?",
      back: "100 €",
      difficulty: 2,
      learningStage: 1,
      topics: ["risque", "volatilité", "calcul"],
      skills: ["quick-calculation"],
      tags: ["risque", "volatilité"],
    },
  ],
};
