import type { Lesson } from "@/lib/types";

export const lessonAnalyseFondamentale: Lesson = {
  id: "mf-found-l2-analyse-fondamentale",
  slug: "analyse-fondamentale",
  title: "Analyse fondamentale et multiples de valorisation",
  description: "Maîtriser les ratios P/E, EV/EBITDA, P/B et les bases de la valorisation",
  estimatedMinutes: 11,
  cards: [
    {
      id: "mf-found-l2-af-def-1a2b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le ratio P/E (Price-to-Earnings) ?",
      shortAnswer:
        "Le P/E est le rapport entre le cours d'une action et le bénéfice par action (BPA). Il indique combien les investisseurs paient pour chaque euro de bénéfice.",
      explanation:
        "P/E = Cours / BPA. Un P/E de 20 signifie que les investisseurs paient 20 € pour 1 € de bénéfice annuel. Les secteurs à forte croissance (tech) ont des P/E élevés (30-50×) ; les secteurs matures ont des P/E plus bas (10-15×).",
      formula: "P/E = Cours de l'action / Bénéfice par action (BPA)",
      front: "Qu'est-ce que le ratio P/E (Price-to-Earnings) ?",
      back: "P/E = Cours / BPA. Combien on paie pour chaque euro de bénéfice.",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "P/E", "multiples"],
      skills: ["definition"],
      tags: ["P/E", "valorisation", "bénéfice"],
    },
    {
      id: "mf-found-l2-af-def-3c4d",
      type: "formula",
      questionType: "formula",
      question: "Comment se calcule l'Enterprise Value (EV) à partir de la capitalisation boursière ?",
      shortAnswer:
        "EV = Capitalisation boursière + Dette financière nette (dettes – trésorerie)",
      explanation:
        "L'EV représente le prix total pour acquérir 100 % d'une entreprise (capitaux propres + dettes). Si vous rachetez une entreprise, vous héritez aussi de sa dette — l'EV en tient compte. Une entreprise avec beaucoup de trésorerie aura une EV inférieure à sa market cap.",
      formula: "EV = Market Cap + Dette nette = Market Cap + Dettes financières − Trésorerie",
      front: "Comment se calcule l'Enterprise Value (EV) ?",
      back: "EV = Market Cap + Dette nette (dettes – trésorerie).",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "EV", "entreprise"],
      skills: ["formula"],
      tags: ["EV", "capitalisation", "dette"],
    },
    {
      id: "mf-found-l2-af-tf-5e6f",
      type: "definition",
      questionType: "true-false",
      question: "Un P/E élevé signifie toujours que l'action est surévaluée.",
      shortAnswer:
        "Faux. Un P/E élevé peut refléter de fortes anticipations de croissance. Une entreprise à +30 % de croissance annuelle peut justifier un P/E de 40× si cette croissance est durable.",
      explanation:
        "Le P/E est relatif au contexte. Amazon a longtemps eu un P/E très élevé parce que les investisseurs anticipaient une forte croissance future. Comparer le P/E d'une biotech avec celui d'une utility serait absurde. L'indicateur PEG (P/E divisé par le taux de croissance) tente de corriger ce biais.",
      correctBool: false,
      front: "Un P/E élevé signifie toujours que l'action est surévaluée.",
      back: "Faux. Un P/E élevé peut refléter de fortes anticipations de croissance.",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "P/E", "croissance"],
      skills: ["definition"],
      tags: ["P/E", "valorisation", "croissance"],
    },
    {
      id: "mf-found-l2-af-mcq-7a8b",
      type: "definition",
      questionType: "comparison",
      question:
        "Quel multiple est le plus adapté pour comparer des entreprises avec des structures de capital différentes (niveaux d'endettement variés) ?",
      shortAnswer: "EV/EBITDA, car il est indépendant de la structure financière.",
      explanation:
        "Le P/E est affecté par la dette (les intérêts réduisent le bénéfice net). L'EBITDA est avant intérêts : EV/EBITDA compare donc des entreprises indépendamment de leur levier. C'est le multiple le plus utilisé en M&A et private equity.",
      front: "Quel multiple pour comparer des entreprises avec des structures de capital différentes ?",
      back: "EV/EBITDA. Il est indépendant du niveau d'endettement.",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "EV/EBITDA", "comparaison"],
      skills: ["comparison"],
      tags: ["EV/EBITDA", "valorisation", "M&A"],
      choices: [
        "EV/EBITDA, car il est indépendant de la structure financière",
        "P/E, car il est le plus simple à calculer",
        "P/B, car il compare la valeur de marché à la valeur comptable",
        "PEG, car il intègre le taux de croissance",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-af-num-9c0d",
      type: "formula",
      questionType: "quick-calculation",
      question:
        "Une entreprise a un bénéfice net de 200 M€ et 50 millions d'actions en circulation. Le cours est à 60 €. Quel est son P/E ?",
      shortAnswer: "15×",
      formula: "P/E = Cours / BPA = Cours / (Bénéfice net / Nombre d'actions)",
      example: "BPA = 200 M€ / 50 M = 4 € par action. P/E = 60 € / 4 € = 15×",
      answerMode: "numeric",
      expectedAnswer: 15,
      answerUnit: "×",
      tolerance: 0.1,
      front: "Bénéfice net = 200 M€, 50 M actions, cours = 60 €. Quel est le P/E ?",
      back: "15×",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "P/E", "calcul"],
      skills: ["quick-calculation"],
      tags: ["P/E", "calcul", "BPA"],
    },
    {
      id: "mf-found-l2-af-tf-1e2f",
      type: "definition",
      questionType: "true-false",
      question:
        "L'Enterprise Value (EV) est toujours supérieure à la capitalisation boursière.",
      shortAnswer:
        "Faux. Si une entreprise a plus de trésorerie que de dette, sa dette nette est négative et l'EV est inférieure à la market cap.",
      explanation:
        "Exemple : entreprise avec market cap 1 Md€, trésorerie 300 M€ et zéro dette → dette nette = −300 M€ → EV = 1 000 − 300 = 700 M€. Certaines entreprises tech très cash-rich ont une EV inférieure à leur capitalisation.",
      correctBool: false,
      front: "L'Enterprise Value (EV) est toujours supérieure à la capitalisation boursière.",
      back: "Faux. Si la trésorerie dépasse les dettes, l'EV < market cap.",
      difficulty: 2,
      learningStage: 1,
      topics: ["valorisation", "EV", "trésorerie"],
      skills: ["formula"],
      tags: ["EV", "capitalisation", "trésorerie"],
    },
    {
      id: "mf-found-l2-af-mcq-3a4b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le ratio P/B (Price-to-Book) mesure ?",
      shortAnswer:
        "Le rapport entre la valeur de marché d'une action et sa valeur comptable (capitaux propres / nombre d'actions).",
      explanation:
        "P/B = Cours / Valeur comptable par action. Un P/B = 1 signifie que le marché valorise exactement la valeur comptable. Un P/B < 1 peut indiquer une décote (ou une inefficience de marché). Les banques et les assureurs sont souvent analysés via le P/B.",
      front: "Qu'est-ce que le ratio P/B (Price-to-Book) mesure ?",
      back: "P/B = Cours / Valeur comptable par action. Rapport entre valeur de marché et valeur comptable.",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "P/B", "multiples"],
      skills: ["definition"],
      tags: ["P/B", "valorisation", "bilan"],
      choices: [
        "Le rapport entre valeur de marché et valeur comptable des capitaux propres",
        "Le rapport entre le cours et le chiffre d'affaires par action",
        "Le rapport entre le cours et le bénéfice net par action",
        "Le rapport entre la dette et les capitaux propres",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-af-num-5c6d",
      type: "formula",
      questionType: "quick-calculation",
      question: "EV = 600 M€, EBITDA = 75 M€. Quel est le multiple EV/EBITDA ?",
      shortAnswer: "8×",
      formula: "EV/EBITDA = Enterprise Value / EBITDA",
      example: "600 / 75 = 8×",
      answerMode: "numeric",
      expectedAnswer: 8,
      answerUnit: "×",
      tolerance: 0.1,
      front: "EV = 600 M€, EBITDA = 75 M€. Quel est le multiple EV/EBITDA ?",
      back: "8×",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "EV/EBITDA", "calcul"],
      skills: ["quick-calculation"],
      tags: ["EV/EBITDA", "calcul", "valorisation"],
    },
    {
      id: "mf-found-l2-af-mcq-7e8f",
      type: "definition",
      questionType: "definition",
      question: "Une entreprise avec P/B < 1 signifie que...",
      shortAnswer:
        "Le marché valorise la société en dessous de sa valeur comptable (valeur des actifs nets au bilan).",
      explanation:
        "Cela peut signifier une décote de marché (crainte de pertes futures, destruction de valeur), une inefficience, ou un business dont les actifs sont difficiles à évaluer. Les banques après 2008 ont longtemps traité à P/B < 1 car le marché doutait de la qualité de leurs actifs.",
      front: "Une entreprise avec P/B < 1 signifie que...",
      back: "Le marché valorise la société sous sa valeur comptable — signal potentiel de décote ou de crainte de pertes.",
      difficulty: 2,
      learningStage: 1,
      topics: ["valorisation", "P/B"],
      skills: ["definition"],
      tags: ["P/B", "valorisation", "décote"],
      choices: [
        "Le marché valorise la société en dessous de sa valeur comptable",
        "L'entreprise est nécessairement en perte",
        "L'entreprise ne verse pas de dividende",
        "Le cours de l'action est inférieur à 1 €",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-af-def-9a0b",
      type: "definition",
      questionType: "mechanism",
      question: "Qu'est-ce que la méthode DCF (Discounted Cash Flow) ?",
      shortAnswer:
        "Le DCF valorise une entreprise en actualisant ses flux de trésorerie futurs estimés au coût du capital. La valeur aujourd'hui = somme des FCF futurs ramenés à leur valeur présente.",
      explanation:
        "C'est la méthode de référence en finance d'entreprise. Elle est sensible aux hypothèses : taux de croissance, taux d'actualisation (WACC). Une petite variation de ces paramètres peut changer considérablement la valorisation. D'où l'importance des analyses de sensibilité.",
      formula: "Valeur = Σ FCFt / (1 + WACC)^t + Valeur terminale / (1 + WACC)^n",
      front: "Qu'est-ce que la méthode DCF (Discounted Cash Flow) ?",
      back: "Valorisation par actualisation des flux de trésorerie futurs au coût du capital (WACC).",
      difficulty: 2,
      learningStage: 1,
      topics: ["valorisation", "DCF", "WACC"],
      skills: ["mechanism"],
      tags: ["DCF", "valorisation", "WACC"],
    },
    {
      id: "mf-found-l2-af-tf-1f2a",
      type: "definition",
      questionType: "true-false",
      question:
        "Le multiple EV/EBITDA d'une entreprise est comparable entre deux entreprises du même secteur avec des structures de dette différentes.",
      shortAnswer:
        "Vrai. C'est précisément l'avantage de l'EV/EBITDA : il est neutre vis-à-vis du financement. Deux entreprises similaires avec des niveaux de dette différents sont comparables via ce multiple.",
      explanation:
        "En M&A, l'acheteur regarde l'EV/EBITDA car il rachète l'entreprise avec ou sans dette (et reprend/rembourse la dette dans tous les cas). En private equity, les transactions LBO se font souvent sur des multiples EV/EBITDA de 8-12× selon le secteur.",
      correctBool: true,
      front: "Le multiple EV/EBITDA est comparable entre entreprises avec des structures de dette différentes.",
      back: "Vrai. C'est sa principale qualité par rapport au P/E.",
      difficulty: 1,
      learningStage: 1,
      topics: ["valorisation", "EV/EBITDA", "comparaison"],
      skills: ["comparison"],
      tags: ["EV/EBITDA", "M&A", "comparaison"],
    },
  ],
};
