import type { Lesson } from "@/lib/types";

export const lessonChange: Lesson = {
  id: "mf-found-l2-change",
  slug: "marche-des-changes",
  title: "Le marché des changes (Forex)",
  description: "Comprendre les cotations de change, les acteurs et les mécanismes du Forex",
  estimatedMinutes: 10,
  cards: [
    {
      id: "mf-found-l2-fx-def-1a2b",
      type: "definition",
      questionType: "definition",
      question: "Comment lire une cotation de change EUR/USD = 1,08 ?",
      shortAnswer:
        "1 euro s'échange contre 1,08 dollars américains. La devise à gauche (EUR) est la devise de base, celle à droite (USD) est la devise cotée.",
      explanation:
        "Lecture : pour acheter 1 EUR, il faut 1,08 USD. Si EUR/USD monte à 1,12, l'euro s'est apprécié (il vaut plus de dollars). Si EUR/USD baisse à 1,05, l'euro s'est déprécié. La devise de base est toujours l'unité de référence.",
      front: "Comment lire EUR/USD = 1,08 ?",
      back: "1 euro = 1,08 dollars. EUR = devise de base (l'unité), USD = devise cotée (le prix).",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "forex", "cotation"],
      skills: ["definition"],
      tags: ["change", "EUR/USD", "cotation"],
    },
    {
      id: "mf-found-l2-fx-mec-3c4d",
      type: "definition",
      questionType: "mechanism",
      question: "Quels sont les principaux facteurs qui influencent les taux de change ?",
      shortAnswer:
        "Différentiels de taux d'intérêt, différentiels d'inflation, balance commerciale, croissance économique relative et anticipations des marchés.",
      explanation:
        "Une hausse des taux d'intérêt dans un pays attire les capitaux étrangers → demande de la devise → appréciation. Une inflation plus élevée érode le pouvoir d'achat → dépréciation. Les annonces des banques centrales (Fed, BCE) sont les principaux catalyseurs des mouvements de change.",
      front: "Quels sont les principaux facteurs qui influencent les taux de change ?",
      back: "Taux d'intérêt, inflation, balance commerciale, croissance et anticipations de marché.",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "macro", "taux-intérêt"],
      skills: ["mechanism"],
      tags: ["change", "macro", "taux"],
    },
    {
      id: "mf-found-l2-fx-tf-5e6f",
      type: "definition",
      questionType: "true-false",
      question: "Le marché des changes (Forex) est le plus grand marché financier mondial.",
      shortAnswer:
        "Vrai. Le Forex traite environ 7 500 milliards de dollars par jour, soit plus que tous les marchés actions mondiaux réunis.",
      explanation:
        "Le Forex est décentralisé (pas de bourse centrale), ouvert 24h/24 du lundi au vendredi, avec des places à Tokyo, Londres et New York qui se relaient. Les paires les plus échangées : EUR/USD (~24 %), USD/JPY (~14 %), GBP/USD (~9 %).",
      correctBool: true,
      front: "Le marché Forex est le plus grand marché financier mondial.",
      back: "Vrai. ~7 500 Mds $/jour, décentralisé, ouvert 24h/24 du lundi au vendredi.",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "forex", "marché"],
      skills: ["market-culture"],
      tags: ["change", "forex", "volume"],
    },
    {
      id: "mf-found-l2-fx-mcq-7a8b",
      type: "definition",
      questionType: "definition",
      question: "Si EUR/USD passe de 1,05 à 1,10, qu'est-il arrivé à l'euro ?",
      shortAnswer: "L'euro s'est apprécié face au dollar (il vaut plus de dollars).",
      explanation:
        "EUR/USD monte → l'euro vaut plus de dollars → euro fort/dollar faible. Inversement, EUR/USD baisse → euro faible/dollar fort. Un euro fort renchérit les exportations européennes en dollars mais réduit le coût des importations (pétrole en $).",
      front: "EUR/USD passe de 1,05 à 1,10. Qu'est-il arrivé à l'euro ?",
      back: "L'euro s'est apprécié face au dollar.",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "appréciation", "dépréciation"],
      skills: ["definition"],
      tags: ["change", "EUR/USD", "appréciation"],
      choices: [
        "L'euro s'est apprécié face au dollar",
        "L'euro s'est déprécié face au dollar",
        "L'euro et le dollar ont évolué de façon identique",
        "Le taux est resté stable, seuls les volumes ont changé",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-fx-tf-9c0d",
      type: "definition",
      questionType: "true-false",
      question:
        "L'appréciation de l'euro est favorable aux exportateurs de la zone euro.",
      shortAnswer:
        "Faux. Un euro fort rend les produits européens plus chers pour les acheteurs étrangers, ce qui nuit aux exportateurs. C'est favorable aux importateurs (achats en dollars moins chers).",
      explanation:
        "Exemple : Airbus vend des avions en dollars. Si EUR/USD monte de 1,05 à 1,15, un avion facturé 200 M$ rapporte moins d'euros (200/1,15 = 174 M€ au lieu de 200/1,05 = 190 M€). Airbus perd des marges à moins de se couvrir en change.",
      correctBool: false,
      front: "L'appréciation de l'euro est favorable aux exportateurs européens.",
      back: "Faux. Un euro fort renchérit les produits européens à l'étranger. C'est défavorable aux exportateurs.",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "exportateurs", "compétitivité"],
      skills: ["mechanism"],
      tags: ["change", "exportateurs", "euro-fort"],
    },
    {
      id: "mf-found-l2-fx-mcq-1e2f",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le carry trade en Forex ?",
      shortAnswer:
        "Emprunter dans une devise à faible taux d'intérêt (ex : yen japonais) pour investir dans une devise à taux élevé (ex : dollar australien), en capturant le différentiel de taux.",
      explanation:
        "Stratégie populaire en période de stabilité : si le yen à 0% et le AUD à 5%, emprunter en JPY et placer en AUD rapporte le spread (≈5%). Risque : si le JPY s'apprécie brusquement, la stratégie peut perdre plus que le carry (comme en 2007-2008 ou août 2024).",
      front: "Qu'est-ce que le carry trade en Forex ?",
      back: "Emprunter dans une devise à taux bas pour investir dans une devise à taux élevé, en capturant le différentiel.",
      difficulty: 2,
      learningStage: 1,
      topics: ["change", "carry-trade", "stratégie"],
      skills: ["definition"],
      tags: ["change", "carry-trade", "taux"],
      choices: [
        "Emprunter dans une devise à taux bas pour investir dans une devise à taux élevé",
        "Acheter une devise et la revendre immédiatement pour capter un arbitrage",
        "Se couvrir contre une variation de change avec des forwards",
        "Acheter des devises refuges (CHF, JPY) en période de crise",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-fx-num-3a4b",
      type: "formula",
      questionType: "quick-calculation",
      question:
        "Vous convertissez 5 000 € en dollars avec EUR/USD = 1,12. Combien obtenez-vous en dollars ?",
      shortAnswer: "5 600 $.",
      formula: "Montant en USD = Montant en EUR × Taux EUR/USD",
      example: "5 000 × 1,12 = 5 600 $",
      answerMode: "numeric",
      expectedAnswer: 5600,
      answerUnit: "$",
      tolerance: 0.01,
      front: "Conversion de 5 000 € avec EUR/USD = 1,12. Combien en dollars ?",
      back: "5 600 $.",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "calcul", "conversion"],
      skills: ["quick-calculation"],
      tags: ["change", "EUR/USD", "calcul"],
    },
    {
      id: "mf-found-l2-fx-def-5c6d",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la parité de pouvoir d'achat (PPA) ?",
      shortAnswer:
        "La PPA est le taux de change théorique qui égaliserait les prix d'un même panier de biens entre deux pays. Elle sert à comparer les niveaux de vie et à évaluer si une devise est sur- ou sous-évaluée.",
      explanation:
        "Le 'Big Mac Index' de The Economist est une version simplifiée de la PPA. Si un Big Mac coûte 5,5 $ aux US et 4,5 € en France, la PPA implicite EUR/USD serait 5,5/4,5 ≈ 1,22. Si EUR/USD marché < 1,22, l'euro serait sous-évalué selon cette mesure.",
      front: "Qu'est-ce que la parité de pouvoir d'achat (PPA) ?",
      back: "Taux théorique qui égalise les prix entre pays. Utilisé pour comparer les niveaux de vie.",
      difficulty: 2,
      learningStage: 1,
      topics: ["change", "PPA", "macro"],
      skills: ["definition"],
      tags: ["change", "PPA", "valorisation"],
    },
    {
      id: "mf-found-l2-fx-mcq-7e8f",
      type: "definition",
      questionType: "definition",
      question: "Le taux de change 'spot' désigne quel type de transaction ?",
      shortAnswer:
        "Une transaction de change à livraison quasi-immédiate, conventionnellement réglée à J+2 (deux jours ouvrés après la date de transaction).",
      explanation:
        "Le marché spot est le marché du change au comptant. Il s'oppose au marché à terme (forward), où l'on fixe aujourd'hui un taux pour une livraison future. Les entreprises qui importent/exportent utilisent des forwards pour se couvrir contre les variations de change.",
      front: "Le taux de change 'spot' désigne quel type de transaction ?",
      back: "Transaction à livraison quasi-immédiate (J+2). S'oppose aux transactions forward (terme).",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "spot", "marché-comptant"],
      skills: ["definition"],
      tags: ["change", "spot", "forward"],
      choices: [
        "Transaction à livraison immédiate (réglée à J+2)",
        "Transaction à livraison dans 30 jours",
        "Échange de devises par une banque centrale",
        "Transaction interbancaire de nuit (overnight)",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-fx-tf-9a0b",
      type: "definition",
      questionType: "true-false",
      question:
        "Une banque centrale peut influencer le taux de change de sa monnaie en intervenant sur le marché des changes.",
      shortAnswer:
        "Vrai. Une banque centrale peut vendre des réserves de change pour acheter sa propre monnaie (soutenir la devise) ou imprimer sa monnaie pour l'affaiblir.",
      explanation:
        "Exemples : la BNS (Banque Nationale Suisse) est intervenue massivement pour affaiblir le franc suisse face à l'euro. La BOJ (Banque du Japon) a vendu des yens pour limiter son appréciation. Toutefois, contre un marché de 7 500 Mds$/jour, les interventions sont limitées sur le long terme.",
      correctBool: true,
      front: "Une banque centrale peut influencer le taux de change de sa monnaie.",
      back: "Vrai. En achetant/vendant des devises sur le marché, mais avec des effets limités sur le long terme.",
      difficulty: 1,
      learningStage: 1,
      topics: ["change", "banque-centrale", "intervention"],
      skills: ["mechanism"],
      tags: ["change", "banque-centrale", "BNS"],
    },
  ],
};
