import type { Lesson } from "@/lib/types";

export const lessonEtf: Lesson = {
  id: "mf-found-l2-etf",
  slug: "etf-gestion-passive",
  title: "ETF et gestion passive",
  description: "Comprendre les ETF, leur fonctionnement et leur montée en puissance",
  estimatedMinutes: 10,
  cards: [
    {
      id: "mf-found-l2-etf-def-1a2b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'un ETF (Exchange-Traded Fund) ?",
      shortAnswer:
        "Un ETF est un fonds d'investissement coté en bourse qui réplique la performance d'un indice ou d'un panier d'actifs. Il se négocie comme une action, en continu, tout au long de la journée.",
      explanation:
        "Les ETF combinent les avantages des fonds (diversification) et des actions (liquidité, cotation continue). La plupart sont passifs (ils suivent un indice) mais il existe des ETF actifs.",
      front: "Qu'est-ce qu'un ETF (Exchange-Traded Fund) ?",
      back: "Un fonds coté en bourse qui réplique un indice. Négociable comme une action, diversifié, et généralement à faible coût.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "gestion-passive"],
      skills: ["definition"],
      tags: ["ETF", "indice", "bourse"],
    },
    {
      id: "mf-found-l2-etf-comp-3c4d",
      type: "definition",
      questionType: "comparison",
      question:
        "Qu'est-ce qui distingue un ETF d'un fonds commun de placement (FCP) traditionnel ?",
      shortAnswer:
        "Un ETF se négocie en continu sur une bourse à un prix qui varie en temps réel. Un FCP ne peut être souscrit ou remboursé qu'une fois par jour, à la valeur liquidative du soir.",
      explanation:
        "Autres différences clés : les ETF ont des frais souvent 5 à 20× inférieurs aux fonds actifs, une fiscalité généralement identique, et une transparence totale sur les titres détenus (portefeuille publié quotidiennement).",
      front: "Qu'est-ce qui distingue un ETF d'un fonds commun de placement traditionnel ?",
      back: "ETF : coté en continu, prix temps réel, frais bas. FCP : valeur liquidative une fois/jour, souvent actif et plus coûteux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "fonds", "comparaison"],
      skills: ["comparison"],
      tags: ["ETF", "FCP", "comparaison"],
    },
    {
      id: "mf-found-l2-etf-tf-5e6f",
      type: "definition",
      questionType: "true-false",
      question: "Tous les ETF sont à gestion passive.",
      shortAnswer:
        "Faux. Il existe des ETF à gestion active, où un gérant prend des décisions discrétionnaires. Cependant, la grande majorité des ETF (en volumes) sont passifs.",
      explanation:
        "Les ETF actifs ont connu une forte croissance, notamment avec ARK Invest aux États-Unis. Mais les ETF indiciels passifs dominent toujours largement : BlackRock iShares, Vanguard et State Street gèrent >60 % du marché des ETF mondial.",
      correctBool: false,
      front: "Tous les ETF sont à gestion passive.",
      back: "Faux. Il existe des ETF actifs. La majorité en volume est passive mais les ETF actifs existent.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "gestion-active", "gestion-passive"],
      skills: ["definition"],
      tags: ["ETF", "gestion-active"],
    },
    {
      id: "mf-found-l2-etf-mcq-7a8b",
      type: "definition",
      questionType: "mechanism",
      question: "La réplication physique d'un ETF consiste à faire quoi ?",
      shortAnswer:
        "Acheter directement les titres composant l'indice de référence, dans les mêmes proportions.",
      explanation:
        "Un ETF S&P 500 à réplication physique détient réellement des actions Apple, Microsoft, Amazon, etc. La réplication peut être totale (tous les titres) ou par échantillonnage optimisé (un sous-ensemble représentatif pour les indices très larges).",
      front: "La réplication physique d'un ETF consiste à faire quoi ?",
      back: "Acheter directement les titres de l'indice dans les mêmes proportions.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "réplication-physique"],
      skills: ["mechanism"],
      tags: ["ETF", "réplication"],
      choices: [
        "Acheter directement les titres composant l'indice dans les mêmes proportions",
        "Utiliser des contrats de swaps pour reproduire la performance de l'indice",
        "Emprunter des titres pour les vendre à découvert",
        "Investir dans des futures sur l'indice",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-etf-tf-9c0d",
      type: "definition",
      questionType: "true-false",
      question: "Un ETF se négocie en continu sur une bourse, comme une action ordinaire.",
      shortAnswer:
        "Vrai. C'est la caractéristique fondamentale des ETF : ils sont cotés et échangés en temps réel pendant les heures de bourse.",
      explanation:
        "Cette liquidité intraday est un avantage par rapport aux fonds traditionnels. Elle permet aussi d'utiliser des ordres à cours limité (limit orders), des ordres stop, ou même de shorter un ETF.",
      correctBool: true,
      front: "Un ETF se négocie en continu sur une bourse, comme une action ordinaire.",
      back: "Vrai. ETF = fonds + cotation continue en bourse.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "liquidité", "bourse"],
      skills: ["definition"],
      tags: ["ETF", "cotation", "liquidité"],
    },
    {
      id: "mf-found-l2-etf-mcq-1e2f",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le tracking error d'un ETF mesure ?",
      shortAnswer:
        "L'écart de performance entre l'ETF et son indice de référence sur une période donnée.",
      explanation:
        "Un tracking error élevé signifie que l'ETF suit mal son indice. Les causes : frais de gestion, traitement des dividendes, coût de rééquilibrage, réplication imparfaite. Les ETF à réplication physique totale ont généralement un tracking error très faible.",
      front: "Qu'est-ce que le tracking error d'un ETF mesure ?",
      back: "L'écart de performance entre l'ETF et son indice de référence.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "tracking-error"],
      skills: ["definition"],
      tags: ["ETF", "tracking-error", "indice"],
      choices: [
        "L'écart de performance entre l'ETF et son indice de référence",
        "Les frais de gestion totaux prélevés chaque année",
        "L'écart entre le prix de marché de l'ETF et sa valeur liquidative",
        "La volatilité annuelle de l'ETF",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-etf-num-3a4b",
      type: "formula",
      questionType: "quick-calculation",
      question:
        "Vous investissez 20 000 € dans un ETF avec un TER (Total Expense Ratio) de 0,20 % par an. Combien payez-vous en frais de gestion annuels ?",
      shortAnswer: "40 €.",
      formula: "Frais annuels = Montant investi × TER",
      example: "20 000 × 0,0020 = 40 €",
      answerMode: "numeric",
      expectedAnswer: 40,
      answerUnit: "€",
      tolerance: 0.01,
      front: "Vous investissez 20 000 € dans un ETF avec un TER de 0,20 % par an. Combien payez-vous en frais de gestion annuels ?",
      back: "40 €.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "TER", "frais"],
      skills: ["quick-calculation"],
      tags: ["ETF", "TER", "calcul"],
    },
    {
      id: "mf-found-l2-etf-def-5c6d",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le TER (Total Expense Ratio) d'un ETF ?",
      shortAnswer:
        "Le TER est le coût annuel total d'un ETF, exprimé en pourcentage des actifs gérés. Il inclut les frais de gestion, les frais administratifs et les coûts de transaction internes.",
      explanation:
        "Les ETF indiciels ont des TER très bas : 0,03-0,20 % pour les grands indices (S&P 500, MSCI World). Les ETF sectoriels ou thématiques peuvent atteindre 0,50-0,75 %. En comparaison, les fonds actifs ont des TER de 1-2 %.",
      front: "Qu'est-ce que le TER (Total Expense Ratio) d'un ETF ?",
      back: "Le coût annuel total exprimé en % des actifs. Ex : 0,20 % pour un ETF indiciel standard.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "TER", "frais"],
      skills: ["definition"],
      tags: ["ETF", "TER", "frais"],
    },
    {
      id: "mf-found-l2-etf-mcq-7e8f",
      type: "definition",
      questionType: "mechanism",
      question: "La réplication synthétique d'un ETF utilise quel instrument financier ?",
      shortAnswer: "Des contrats de swaps pour reproduire la performance de l'indice sans détenir les titres directement.",
      explanation:
        "L'ETF synthétique conclut un swap avec une contrepartie (souvent une banque) : la contrepartie verse la performance de l'indice, et l'ETF verse le rendement d'un panier de collatéral. Avantage : accès à des marchés difficiles (matières premières, émergents). Inconvénient : risque de contrepartie.",
      front: "La réplication synthétique d'un ETF utilise quel instrument financier ?",
      back: "Des contrats de swaps avec une contrepartie bancaire.",
      difficulty: 2,
      learningStage: 1,
      topics: ["ETF", "réplication-synthétique", "swap"],
      skills: ["mechanism"],
      tags: ["ETF", "swap", "réplication"],
      choices: [
        "Des contrats de swaps avec une contrepartie bancaire",
        "Des options sur indices",
        "Des contrats futures sur l'indice",
        "Des obligations convertibles",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-etf-tf-9a0b",
      type: "definition",
      questionType: "true-false",
      question:
        "Les ETF indiciels sont généralement moins coûteux que les fonds à gestion active.",
      shortAnswer:
        "Vrai. Les ETF indiciels ont des TER de 0,03-0,20 %, contre 1-2 % pour les fonds actifs. Sur 30 ans, cet écart de frais peut représenter des dizaines de milliers d'euros.",
      explanation:
        "C'est la proposition de valeur centrale de la gestion passive : la majorité des gérants actifs ne battent pas leur indice sur longue période après frais (études SPIVA). Des frais bas = plus de performance nette pour l'investisseur.",
      correctBool: true,
      front: "Les ETF indiciels sont généralement moins coûteux que les fonds à gestion active.",
      back: "Vrai. TER ETF : 0,03-0,20 %. TER fonds actifs : 1-2 %. L'écart s'accumule considérablement sur le long terme.",
      difficulty: 1,
      learningStage: 1,
      topics: ["ETF", "gestion-passive", "frais"],
      skills: ["definition"],
      tags: ["ETF", "frais", "gestion-active"],
    },
  ],
};
