import type { Lesson } from "@/lib/types";

export const lessonFutures: Lesson = {
  id: "mf-found-l2-futures",
  slug: "introduction-aux-futures",
  title: "Introduction aux futures",
  description: "Comprendre les contrats à terme, leur fonctionnement et leurs usages",
  estimatedMinutes: 10,
  cards: [
    {
      id: "mf-found-l2-fut-def-1a2b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'un contrat futures ?",
      shortAnswer:
        "Un contrat futures est un accord standardisé pour acheter ou vendre un actif à un prix fixé, à une date future déterminée. Les deux parties sont obligées d'honorer le contrat.",
      explanation:
        "Les futures sont négociés sur des marchés organisés (CME, Euronext). Ils portent sur des matières premières (pétrole, blé, or), des indices boursiers (S&P 500 futures), des taux d'intérêt ou des devises. Ils servent à la couverture (hedging) et à la spéculation.",
      front: "Qu'est-ce qu'un contrat futures ?",
      back: "Accord standardisé d'achat/vente d'un actif à un prix et une date fixés. Les deux parties sont obligées.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "dérivés", "contrat-à-terme"],
      skills: ["definition"],
      tags: ["futures", "dérivés", "contrat-à-terme"],
    },
    {
      id: "mf-found-l2-fut-comp-3c4d",
      type: "definition",
      questionType: "comparison",
      question:
        "Quelle est la différence fondamentale entre un futures et une option ?",
      shortAnswer:
        "Un futures est une obligation pour les deux parties (acheteur et vendeur). Une option donne un droit à l'acheteur mais pas une obligation.",
      explanation:
        "L'acheteur d'un futures DOIT acheter à l'échéance (ou clôturer avant). L'acheteur d'une option peut ne pas exercer. Conséquence : le futures peut générer des pertes illimitées pour l'acheteur (si le prix baisse indéfiniment), alors que la perte de l'acheteur d'option est limitée à la prime.",
      front: "Quelle est la différence fondamentale entre un futures et une option ?",
      back: "Futures = obligation bilatérale. Option = droit pour l'acheteur, obligation pour le vendeur.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "options", "comparaison"],
      skills: ["comparison"],
      tags: ["futures", "options", "droit-obligation"],
    },
    {
      id: "mf-found-l2-fut-tf-5e6f",
      type: "definition",
      questionType: "true-false",
      question:
        "L'acheteur d'un futures peut clôturer sa position avant l'échéance en vendant un contrat identique.",
      shortAnswer:
        "Vrai. La grande majorité des futures ne sont jamais livrés physiquement : les positions sont clôturées avant l'échéance par une transaction inverse.",
      explanation:
        "Si vous avez acheté 1 futures pétrole à 80 $/baril, vous pouvez le revendre à 85 $/baril avant l'échéance et encaisser la différence. Moins de 5 % des contrats futures se terminent par une livraison physique.",
      correctBool: true,
      front: "L'acheteur d'un futures peut clôturer sa position avant l'échéance.",
      back: "Vrai. Il vend un contrat identique. La livraison physique est rare (<5% des cas).",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "clôture", "livraison"],
      skills: ["definition"],
      tags: ["futures", "clôture", "livraison"],
    },
    {
      id: "mf-found-l2-fut-mcq-7a8b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que l'appel de marge (margin call) dans le contexte des futures ?",
      shortAnswer:
        "Une demande de versement supplémentaire adressée à un investisseur dont les pertes ont réduit le dépôt de garantie en dessous du niveau minimum requis.",
      explanation:
        "À l'ouverture d'un futures, on dépose une marge initiale (initial margin). Si les pertes quotidiennes font descendre le compte sous la maintenance margin, la chambre de compensation exige un dépôt immédiat. Faute de paiement, la position est forcément liquidée.",
      front: "Qu'est-ce qu'un appel de marge (margin call) dans les futures ?",
      back: "Demande de dépôt supplémentaire quand les pertes font descendre la marge sous le niveau minimum.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "marge", "appel-de-marge"],
      skills: ["definition"],
      tags: ["futures", "marge", "margin-call"],
      choices: [
        "Demande de dépôt supplémentaire quand la marge tombe sous le seuil minimum",
        "La commission versée au broker pour ouvrir une position futures",
        "L'obligation de livrer physiquement l'actif à l'échéance",
        "La différence entre le prix spot et le prix futures",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-fut-tf-9c0d",
      type: "definition",
      questionType: "true-false",
      question:
        "Le prix d'un futures sur une action est toujours égal au prix spot de cette action.",
      shortAnswer:
        "Faux. Le prix du futures intègre le coût de portage (taux d'intérêt moins dividendes attendus). En général, futures > spot (marché en contango) si les taux > dividendes.",
      explanation:
        "Relation de parité : F = S × (1 + r − d) × T, où r = taux d'intérêt, d = dividende attendu, T = temps jusqu'à l'échéance. Pour un futures à 3 mois sur une action sans dividende avec taux à 5% : F ≈ S × 1,0125.",
      correctBool: false,
      front: "Le prix d'un futures sur action est toujours égal au prix spot.",
      back: "Faux. Futures = Spot × (1 + taux − dividendes) jusqu'à échéance.",
      difficulty: 2,
      learningStage: 1,
      topics: ["futures", "pricing", "cost-of-carry"],
      skills: ["mechanism"],
      tags: ["futures", "pricing", "contango"],
    },
    {
      id: "mf-found-l2-fut-mcq-1e2f",
      type: "definition",
      questionType: "mechanism",
      question: "Que signifie le 'marking to market' d'un contrat futures ?",
      shortAnswer:
        "Le P&L est calculé et réglé en cash quotidiennement. Les gains sont crédités et les pertes débitées chaque soir sur le compte de marge.",
      explanation:
        "Contrairement à une obligation qu'on peut détenir jusqu'à maturité sans voir les pertes latentes, les futures sont 'marked to market' : les gains et pertes sont réels quotidiennement. Cela garantit l'intégrité financière du système et limite le risque de contrepartie.",
      front: "Que signifie le 'marking to market' d'un futures ?",
      back: "P&L calculé et réglé quotidiennement en cash. Gains crédités, pertes débitées chaque soir.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "marking-to-market", "règlement"],
      skills: ["mechanism"],
      tags: ["futures", "marking-to-market", "marge"],
      choices: [
        "P&L calculé et réglé quotidiennement en cash sur le compte de marge",
        "Livraison physique de l'actif à la valeur de marché actuelle",
        "Revalorisation du dépôt de garantie selon l'inflation",
        "Publication quotidienne du prix officiel de clôture",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-fut-num-3a4b",
      type: "formula",
      questionType: "quick-calculation",
      question:
        "Vous êtes acheteur de 2 contrats futures sur l'or à 2 000 $/once. Chaque contrat porte sur 100 onces. Le cours monte à 2 050 $. Quel est votre gain total ?",
      shortAnswer: "10 000 $.",
      formula: "Gain = (Prix final − Prix initial) × Taille du contrat × Nombre de contrats",
      example: "(2 050 − 2 000) × 100 × 2 = 50 × 100 × 2 = 10 000 $",
      answerMode: "numeric",
      expectedAnswer: 10000,
      answerUnit: "$",
      tolerance: 0.01,
      front: "Acheteur de 2 contrats futures or à 2 000 $/once (100 oz/contrat). Cours monte à 2 050 $. Gain total ?",
      back: "10 000 $.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "calcul", "P&L"],
      skills: ["quick-calculation"],
      tags: ["futures", "or", "calcul"],
    },
    {
      id: "mf-found-l2-fut-def-5c6d",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la 'base' (basis) dans les marchés à terme ?",
      shortAnswer:
        "La base est la différence entre le prix spot et le prix futures d'un actif. Elle reflète le coût de portage (taux d'intérêt, coûts de stockage, dividendes).",
      explanation:
        "Base = Prix spot − Prix futures. Elle converge vers zéro à l'approche de l'échéance. La gestion du risque de base (basis risk) est importante pour les hedgers : même si on s'est couvert avec des futures, la base peut varier et générer des gains ou pertes résiduels.",
      formula: "Base = Prix spot − Prix futures",
      front: "Qu'est-ce que la 'base' (basis) dans les marchés à terme ?",
      back: "Différence entre prix spot et prix futures. Converge vers 0 à l'échéance.",
      difficulty: 2,
      learningStage: 1,
      topics: ["futures", "basis", "pricing"],
      skills: ["definition"],
      tags: ["futures", "basis", "coût-de-portage"],
    },
    {
      id: "mf-found-l2-fut-mcq-7e8f",
      type: "definition",
      questionType: "market-culture",
      question:
        "Quelle industrie utilise typiquement des futures sur le pétrole pour se couvrir contre la hausse des prix ?",
      shortAnswer: "Les compagnies aériennes, pour se couvrir contre la hausse du kérosène.",
      explanation:
        "Une compagnie aérienne comme Air France peut acheter des futures sur le pétrole (ou utiliser des swaps) pour bloquer le prix de son carburant. Si le kérosène monte, le gain sur les futures compense le surcoût. C'est l'usage classique du hedging avec des dérivés.",
      front: "Quelle industrie utilise typiquement des futures pétrole pour se couvrir ?",
      back: "Les compagnies aériennes, pour se protéger contre la hausse du prix du kérosène.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "hedging", "pétrole"],
      skills: ["market-culture"],
      tags: ["futures", "hedging", "kérosène"],
      choices: [
        "Les compagnies aériennes (kérosène)",
        "Les banques d'investissement (taux d'intérêt)",
        "Les assureurs (volatilité)",
        "Les fonds de pension (actions)",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-fut-tf-9a0b",
      type: "definition",
      questionType: "true-false",
      question:
        "Les contrats futures sont des instruments standardisés négociés sur des marchés organisés (bourses).",
      shortAnswer:
        "Vrai. Contrairement aux forwards (OTC, contrats de gré à gré), les futures sont standardisés et négociés sur des bourses spécialisées comme le CME aux États-Unis ou Euronext.",
      explanation:
        "La standardisation (taille du contrat, dates d'échéance, règles de livraison) permet la liquidité. La chambre de compensation (CCP) se substitue à la contrepartie pour chaque trade, éliminant le risque de contrepartie bilatéral.",
      correctBool: true,
      front: "Les futures sont des instruments standardisés négociés sur des marchés organisés.",
      back: "Vrai. Contrairement aux forwards (OTC), ils sont standardisés et négociés en bourse.",
      difficulty: 1,
      learningStage: 1,
      topics: ["futures", "marché-organisé", "standardisation"],
      skills: ["definition"],
      tags: ["futures", "CME", "standardisation"],
    },
  ],
};
