import type { Lesson } from "@/lib/types";

export const lessonIndices: Lesson = {
  id: "mf-found-l2-indices",
  slug: "indices-boursiers",
  title: "Les indices boursiers",
  description: "Comprendre ce que mesurent les indices et comment ils sont construits",
  estimatedMinutes: 10,
  cards: [
    {
      id: "mf-found-l2-indices-def-1a2b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'un indice boursier ?",
      shortAnswer:
        "Un indice boursier est un panier de titres représentatif d'un marché ou d'un segment. Il mesure l'évolution d'un ensemble d'actions en un seul chiffre.",
      explanation:
        "Les indices servent de baromètre pour les marchés (CAC 40 pour la France, S&P 500 pour les grandes capitalisations américaines) et de benchmark pour évaluer la performance des gérants.",
      front: "Qu'est-ce qu'un indice boursier ?",
      back: "Un panier de titres représentatif d'un marché ou d'un segment, mesurant leur évolution en un seul chiffre.",
      difficulty: 1,
      learningStage: 1,
      topics: ["indices", "marché"],
      skills: ["definition"],
      tags: ["indices", "CAC40", "benchmark"],
    },
    {
      id: "mf-found-l2-indices-mec-3c4d",
      type: "definition",
      questionType: "mechanism",
      question: "Comment fonctionne la pondération par capitalisation boursière dans un indice ?",
      shortAnswer:
        "Chaque titre pèse proportionnellement à sa capitalisation boursière. Plus une entreprise vaut cher en bourse, plus elle influence l'indice.",
      explanation:
        "Exemple : si Apple représente 7 % du S&P 500 et progresse de 10 %, l'indice gagne environ 0,7 % toutes choses égales. La majorité des grands indices mondiaux (S&P 500, CAC 40, MSCI World) utilisent cette méthode.",
      front: "Comment fonctionne la pondération par capitalisation boursière dans un indice ?",
      back: "Chaque titre pèse proportionnellement à sa capitalisation boursière. Les plus grosses entreprises influencent davantage l'indice.",
      difficulty: 1,
      learningStage: 1,
      topics: ["indices", "pondération", "capitalisation"],
      skills: ["mechanism"],
      tags: ["indices", "pondération", "S&P500"],
    },
    {
      id: "mf-found-l2-indices-mcq-5e6f",
      type: "definition",
      questionType: "definition",
      question: "Quel grand indice américain est pondéré par le prix des actions (price-weighted) ?",
      shortAnswer: "Le Dow Jones Industrial Average (DJIA).",
      explanation:
        "Dans un indice price-weighted, une action avec un prix unitaire plus élevé pèse davantage, indépendamment de la taille réelle de l'entreprise. C'est une méthode ancienne et aujourd'hui minoritaire. Le S&P 500 et le MSCI World sont pondérés par capitalisation.",
      front: "Quel grand indice américain est pondéré par le prix des actions (price-weighted) ?",
      back: "Le Dow Jones Industrial Average (DJIA).",
      difficulty: 1,
      learningStage: 1,
      topics: ["indices", "Dow-Jones"],
      skills: ["definition"],
      tags: ["indices", "Dow-Jones", "price-weighted"],
      choices: [
        "Le Dow Jones Industrial Average (DJIA)",
        "Le S&P 500",
        "Le Nasdaq 100",
        "Le Russell 2000",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-indices-tf-7a8b",
      type: "definition",
      questionType: "true-false",
      question:
        "Un indice price-weighted donne plus de poids aux entreprises avec la plus grande capitalisation boursière.",
      shortAnswer:
        "Faux. Un indice price-weighted donne plus de poids aux actions avec le prix unitaire le plus élevé, pas à celles avec la capitalisation la plus élevée.",
      explanation:
        "C'est la confusion classique. Apple à 200 $ pèse deux fois plus que Berkshire Hathaway à 100 $ dans un price-weighted index, même si Berkshire est plus grosse en market cap. Le Dow Jones est l'exemple typique.",
      correctBool: false,
      front: "Un indice price-weighted donne plus de poids aux entreprises avec la plus grande capitalisation boursière.",
      back: "Faux. Il donne plus de poids aux actions avec le prix unitaire le plus élevé.",
      difficulty: 2,
      learningStage: 1,
      topics: ["indices", "pondération"],
      skills: ["definition"],
      tags: ["indices", "price-weighted"],
    },
    {
      id: "mf-found-l2-indices-mcq-9c0d",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le free float dans le calcul d'un indice boursier ?",
      shortAnswer:
        "La part des actions effectivement disponibles à l'échange sur le marché (hors participations des fondateurs, États ou actionnaires bloqués).",
      explanation:
        "La plupart des indices modernes (CAC 40, S&P 500) utilisent le free float pour pondérer les titres. Cela évite de surpondérer des entreprises dont une grande partie des actions n'est pas librement échangeable.",
      front: "Qu'est-ce que le free float dans le calcul d'un indice boursier ?",
      back: "La part des actions disponibles à l'échange, hors participations stables des fondateurs ou États.",
      difficulty: 1,
      learningStage: 1,
      topics: ["indices", "free-float"],
      skills: ["definition"],
      tags: ["indices", "free-float", "capitalisation"],
      choices: [
        "La part des actions disponibles à l'échange (hors participations stables)",
        "Le nombre total d'actions émises par l'entreprise",
        "La valeur comptable des capitaux propres",
        "La trésorerie disponible de l'entreprise",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-indices-num-1e2f",
      type: "formula",
      questionType: "quick-calculation",
      question:
        "Le CAC 40 est à 7 800 points. Il progresse de 2,5 %. À combien se situe-t-il désormais ?",
      shortAnswer: "7 995 points.",
      formula: "Niveau final = Niveau initial × (1 + variation%)",
      example: "7 800 × 1,025 = 7 995",
      answerMode: "numeric",
      expectedAnswer: 7995,
      answerUnit: "points",
      tolerance: 1,
      front: "Le CAC 40 est à 7 800 points. Il progresse de 2,5 %. À combien se situe-t-il désormais ?",
      back: "7 995 points.",
      difficulty: 1,
      learningStage: 1,
      topics: ["indices", "calcul"],
      skills: ["quick-calculation"],
      tags: ["indices", "CAC40", "calcul"],
    },
    {
      id: "mf-found-l2-indices-comp-3a4b",
      type: "definition",
      questionType: "comparison",
      question:
        "Quelle est la différence entre un indice price return et un indice total return ?",
      shortAnswer:
        "Un indice price return ne tient compte que des variations de cours. Un indice total return réinvestit également les dividendes versés.",
      explanation:
        "Sur le long terme, la différence est significative. Le DAX allemand est un indice total return, ce qui le rend difficilement comparable aux indices price return comme le CAC 40 ou le S&P 500 (version courante).",
      front: "Quelle est la différence entre un indice price return et un indice total return ?",
      back: "Price return = variations de cours uniquement. Total return = cours + dividendes réinvestis.",
      difficulty: 2,
      learningStage: 1,
      topics: ["indices", "dividende", "rendement"],
      skills: ["comparison"],
      tags: ["indices", "total-return", "dividende"],
    },
    {
      id: "mf-found-l2-indices-tf-5c6d",
      type: "definition",
      questionType: "true-false",
      question: "Le MSCI World couvre uniquement les marchés développés.",
      shortAnswer:
        "Vrai. Le MSCI World couvre ~23 pays développés. Pour les émergents, il faut le MSCI Emerging Markets, et pour les deux réunis, le MSCI ACWI.",
      explanation:
        "Le MSCI World est souvent mal nommé : il n'inclut pas la Chine, l'Inde ou le Brésil. Il représente environ 85 % de la capitalisation des marchés développés (États-Unis, Europe, Japon…). Le MSCI ACWI est l'indice global réel.",
      correctBool: true,
      front: "Le MSCI World couvre uniquement les marchés développés.",
      back: "Vrai. Les émergents sont dans le MSCI Emerging Markets. Le MSCI ACWI combine les deux.",
      difficulty: 2,
      learningStage: 1,
      topics: ["indices", "MSCI", "marchés-développés"],
      skills: ["definition"],
      tags: ["indices", "MSCI", "émergents"],
    },
    {
      id: "mf-found-l2-indices-mcq-7e8f",
      type: "definition",
      questionType: "market-culture",
      question: "Quel est le principal indice représentant les grandes capitalisations américaines ?",
      shortAnswer: "Le S&P 500, composé des 500 plus grandes entreprises américaines cotées.",
      explanation:
        "Le S&P 500 est la référence mondiale pour la performance des actions américaines. Il représente environ 80 % de la capitalisation totale du marché actions US. Le Nasdaq 100, lui, est axé sur la technologie (non-financials).",
      front: "Quel est le principal indice représentant les grandes capitalisations américaines ?",
      back: "Le S&P 500, composé des 500 plus grandes entreprises américaines cotées.",
      difficulty: 1,
      learningStage: 1,
      topics: ["indices", "S&P500", "US"],
      skills: ["market-culture"],
      tags: ["indices", "S&P500", "US"],
      choices: [
        "Le S&P 500",
        "Le Dow Jones Industrial Average",
        "Le Nasdaq Composite",
        "Le Russell 3000",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-indices-tf-9a0b",
      type: "definition",
      questionType: "true-false",
      question:
        "Un ETF CAC 40 reproduit la performance de l'indice dividendes inclus (total return).",
      shortAnswer:
        "Faux. Par défaut, la plupart des ETF CAC 40 grand public suivent l'indice CAC 40 price return (sans dividendes). Il existe des variantes total return mais elles ne sont pas la version standard.",
      explanation:
        "Le CAC 40 «classique» est un indice price return. Certains ETF suivent le CAC 40 NR (Net Return) qui tient compte des dividendes nets. Il faut vérifier le prospectus de l'ETF.",
      correctBool: false,
      front: "Un ETF CAC 40 reproduit la performance de l'indice dividendes inclus (total return).",
      back: "Faux. Le CAC 40 standard est price return. Il existe des variantes NR mais ce n'est pas la version par défaut.",
      difficulty: 2,
      learningStage: 1,
      topics: ["indices", "ETF", "dividende"],
      skills: ["definition"],
      tags: ["indices", "CAC40", "dividende"],
    },
  ],
};
