import type { Lesson } from "@/lib/types";

export const lessonOptions: Lesson = {
  id: "mf-found-l2-options",
  slug: "introduction-aux-options",
  title: "Introduction aux options",
  description: "Comprendre calls, puts, prime et valeur intrinsèque",
  estimatedMinutes: 11,
  cards: [
    {
      id: "mf-found-l2-opt-def-1a2b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'une option call ?",
      shortAnswer:
        "Une option call donne à son acheteur le droit (mais pas l'obligation) d'acheter un actif sous-jacent à un prix fixé (le strike), avant ou à la date d'échéance.",
      explanation:
        "L'acheteur du call paie une prime pour ce droit. Il exercera l'option seulement si le cours dépasse le strike (sinon, il abandonne l'option et perd uniquement la prime). Le vendeur du call, lui, a l'obligation de vendre si l'acheteur exerce.",
      front: "Qu'est-ce qu'une option call ?",
      back: "Droit d'acheter un actif à un prix fixé (strike) avant l'échéance, contre le paiement d'une prime.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "call", "dérivés"],
      skills: ["definition"],
      tags: ["options", "call", "dérivés"],
    },
    {
      id: "mf-found-l2-opt-def-3c4d",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce qu'une option put ?",
      shortAnswer:
        "Une option put donne à son acheteur le droit (mais pas l'obligation) de vendre un actif sous-jacent au prix du strike, avant ou à l'échéance.",
      explanation:
        "L'acheteur d'un put gagne si le cours baisse sous le strike. C'est un instrument de protection (couverture) : un investisseur long sur une action peut acheter un put pour se couvrir contre une baisse. On parle de 'put de protection' ou 'protective put'.",
      front: "Qu'est-ce qu'une option put ?",
      back: "Droit de vendre un actif au strike avant l'échéance. Profite si le cours baisse.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "put", "dérivés"],
      skills: ["definition"],
      tags: ["options", "put", "dérivés"],
    },
    {
      id: "mf-found-l2-opt-tf-5e6f",
      type: "definition",
      questionType: "true-false",
      question: "L'acheteur d'une option call est obligé d'acheter l'actif sous-jacent à l'échéance.",
      shortAnswer:
        "Faux. L'acheteur a un droit, pas une obligation. Il exercera le call seulement si cela lui est favorable (cours > strike). Sinon, il laisse expirer l'option et perd uniquement la prime.",
      explanation:
        "C'est la différence fondamentale entre une option et un futures. Le futures oblige les deux parties. L'option ne lie que le vendeur (qui doit livrer si l'acheteur exerce), pas l'acheteur.",
      correctBool: false,
      front: "L'acheteur d'un call est obligé d'acheter l'actif sous-jacent à l'échéance.",
      back: "Faux. Il a un droit, pas une obligation. Il peut laisser expirer l'option.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "droit-obligation", "call"],
      skills: ["definition"],
      tags: ["options", "call", "droit"],
    },
    {
      id: "mf-found-l2-opt-mcq-7a8b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que le strike (prix d'exercice) d'une option ?",
      shortAnswer:
        "Le prix auquel le détenteur de l'option peut acheter (call) ou vendre (put) le sous-jacent.",
      explanation:
        "Le strike est fixé à la création du contrat. Il ne change pas jusqu'à l'échéance. Un call avec strike 100 € sur une action à 110 € est 'in the money' de 10 €. Un call avec strike 120 € sur la même action est 'out of the money'.",
      front: "Qu'est-ce que le strike (prix d'exercice) d'une option ?",
      back: "Le prix fixé à la création auquel on peut acheter (call) ou vendre (put) le sous-jacent.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "strike", "prix-exercice"],
      skills: ["definition"],
      tags: ["options", "strike", "call", "put"],
      choices: [
        "Le prix auquel le détenteur peut acheter ou vendre le sous-jacent",
        "Le prix actuel de l'option sur le marché",
        "La prime payée pour acquérir l'option",
        "Le cours du sous-jacent à la date d'achat de l'option",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-opt-tf-9c0d",
      type: "definition",
      questionType: "true-false",
      question: "La perte maximale pour l'acheteur d'une option est limitée à la prime payée.",
      shortAnswer:
        "Vrai. L'acheteur d'une option (call ou put) ne peut perdre que ce qu'il a payé (la prime). C'est l'un des attraits des options comme instrument de couverture.",
      explanation:
        "En revanche, le vendeur (le 'writer') d'une option a un risque potentiellement illimité (pour un call vendu nu : si le sous-jacent monte indéfiniment). C'est pourquoi les vendeurs d'options ont des exigences de marge élevées.",
      correctBool: true,
      front: "La perte maximale pour l'acheteur d'une option est limitée à la prime payée.",
      back: "Vrai. Acheteur d'option : risque limité à la prime. Vendeur : risque potentiellement illimité.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "prime", "risque"],
      skills: ["definition"],
      tags: ["options", "prime", "risque"],
    },
    {
      id: "mf-found-l2-opt-mcq-1e2f",
      type: "definition",
      questionType: "definition",
      question: "Un call est dit 'in the money' (dans la monnaie) quand...",
      shortAnswer: "Le cours du sous-jacent est supérieur au strike.",
      explanation:
        "In the money (ITM) : cours > strike pour un call (ou cours < strike pour un put). Out of the money (OTM) : l'inverse. At the money (ATM) : cours ≈ strike. La valeur intrinsèque d'un call ITM est : cours − strike.",
      front: "Un call est dit 'in the money' quand...",
      back: "Cours du sous-jacent > strike. La valeur intrinsèque est cours − strike.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "in-the-money", "valeur-intrinsèque"],
      skills: ["definition"],
      tags: ["options", "ITM", "strike"],
      choices: [
        "Le cours du sous-jacent est supérieur au strike",
        "Le cours du sous-jacent est égal au strike",
        "Le cours du sous-jacent est inférieur au strike",
        "La prime est supérieure à la valeur intrinsèque",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-opt-num-3a4b",
      type: "formula",
      questionType: "quick-calculation",
      question:
        "Strike d'un call = 50 €, cours actuel du sous-jacent = 58 €. Quelle est la valeur intrinsèque de ce call ?",
      shortAnswer: "8 €.",
      formula: "Valeur intrinsèque du call = max(Cours − Strike, 0)",
      example: "max(58 − 50, 0) = max(8, 0) = 8 €",
      answerMode: "numeric",
      expectedAnswer: 8,
      answerUnit: "€",
      tolerance: 0.01,
      front: "Call avec strike 50 €, cours = 58 €. Quelle est la valeur intrinsèque ?",
      back: "8 € (= 58 − 50).",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "valeur-intrinsèque", "calcul"],
      skills: ["quick-calculation"],
      tags: ["options", "valeur-intrinsèque", "calcul"],
    },
    {
      id: "mf-found-l2-opt-mcq-5c6d",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la valeur temps d'une option ?",
      shortAnswer:
        "La partie de la prime d'une option au-delà de sa valeur intrinsèque. Elle reflète la probabilité que l'option devienne plus rentable avant l'échéance.",
      explanation:
        "Prime = Valeur intrinsèque + Valeur temps. La valeur temps décroît avec le temps ('time decay' ou thêta). Une option ATM a une valeur temps maximale. La valeur temps dépend de la volatilité, du temps restant et de l'éloignement du strike.",
      formula: "Valeur temps = Prime totale − Valeur intrinsèque",
      front: "Qu'est-ce que la valeur temps d'une option ?",
      back: "Prime − Valeur intrinsèque. Elle représente la probabilité que l'option devienne plus profitable avant l'échéance.",
      difficulty: 2,
      learningStage: 1,
      topics: ["options", "valeur-temps", "prime"],
      skills: ["definition"],
      tags: ["options", "valeur-temps", "thêta"],
      choices: [
        "La prime au-delà de la valeur intrinsèque, liée au temps restant et à la volatilité",
        "Le temps restant jusqu'à l'échéance de l'option en jours",
        "La différence entre le prix du call et du put de même strike",
        "Le coût de portage de la position jusqu'à l'échéance",
      ],
      correctIndex: 0,
    },
    {
      id: "mf-found-l2-opt-tf-7e8f",
      type: "definition",
      questionType: "true-false",
      question: "La valeur temps d'une option est toujours positive ou nulle.",
      shortAnswer:
        "Vrai. La prime d'une option est toujours ≥ à sa valeur intrinsèque. La valeur temps est donc toujours ≥ 0.",
      explanation:
        "Logique d'arbitrage : si la prime était inférieure à la valeur intrinsèque, on pourrait acheter l'option, l'exercer immédiatement et réaliser un profit sans risque. Le marché élimine ces arbitrages instantanément.",
      correctBool: true,
      front: "La valeur temps d'une option est toujours positive ou nulle.",
      back: "Vrai. Prime ≥ Valeur intrinsèque, donc valeur temps ≥ 0 (sinon il y aurait arbitrage).",
      difficulty: 2,
      learningStage: 1,
      topics: ["options", "valeur-temps", "arbitrage"],
      skills: ["definition"],
      tags: ["options", "valeur-temps", "arbitrage"],
    },
    {
      id: "mf-found-l2-opt-def-9a0b",
      type: "definition",
      questionType: "definition",
      question: "Qu'est-ce que la volatilité implicite d'une option ?",
      shortAnswer:
        "La volatilité que le marché 'intègre' dans le prix d'une option. Elle représente l'anticipation du marché concernant les mouvements futurs du sous-jacent.",
      explanation:
        "Plus la volatilité implicite est élevée, plus les options sont chères. L'indice VIX mesure la volatilité implicite des options sur le S&P 500 — c'est le 'baromètre de la peur' des marchés. En période de stress, le VIX monte fortement.",
      front: "Qu'est-ce que la volatilité implicite d'une option ?",
      back: "La volatilité future anticipée par le marché, intégrée dans le prix de l'option. Plus elle est élevée, plus l'option est chère.",
      difficulty: 2,
      learningStage: 1,
      topics: ["options", "volatilité-implicite", "VIX"],
      skills: ["definition"],
      tags: ["options", "volatilité", "VIX"],
    },
    {
      id: "mf-found-l2-opt-mcq-1f2a",
      type: "definition",
      questionType: "market-culture",
      question:
        "Le VIX ('indice de la peur') mesure la volatilité implicite de quel indice boursier ?",
      shortAnswer: "Le S&P 500.",
      explanation:
        "Le VIX, calculé par le CBOE, reflète la volatilité implicite des options sur le S&P 500 à 30 jours. Un VIX > 30 signale une forte anxiété sur les marchés. Pendant la crise du Covid (mars 2020), le VIX a dépassé 80.",
      front: "Le VIX mesure la volatilité implicite de quel indice ?",
      back: "Le S&P 500. VIX > 30 = marché très anxieux.",
      difficulty: 1,
      learningStage: 1,
      topics: ["options", "VIX", "volatilité"],
      skills: ["market-culture"],
      tags: ["VIX", "options", "S&P500"],
      choices: [
        "Le S&P 500",
        "Le Nasdaq 100",
        "Le Dow Jones Industrial Average",
        "L'Euro Stoxx 50",
      ],
      correctIndex: 0,
    },
  ],
};
